// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: bulk.proto

package evm

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BulkQueryService_GetBlocksByRange_FullMethodName = "/bds.evm.BulkQueryService/GetBlocksByRange"
)

// BulkQueryServiceClient is the client API for BulkQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service for bulk EVM blockchain data operations
// Designed for high-throughput data extraction and analytics use cases
type BulkQueryServiceClient interface {
	// Get multiple blocks within a range in a single request
	GetBlocksByRange(ctx context.Context, in *GetBlocksByRangeRequest, opts ...grpc.CallOption) (*GetBlocksByRangeResponse, error)
}

type bulkQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBulkQueryServiceClient(cc grpc.ClientConnInterface) BulkQueryServiceClient {
	return &bulkQueryServiceClient{cc}
}

func (c *bulkQueryServiceClient) GetBlocksByRange(ctx context.Context, in *GetBlocksByRangeRequest, opts ...grpc.CallOption) (*GetBlocksByRangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBlocksByRangeResponse)
	err := c.cc.Invoke(ctx, BulkQueryService_GetBlocksByRange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BulkQueryServiceServer is the server API for BulkQueryService service.
// All implementations must embed UnimplementedBulkQueryServiceServer
// for forward compatibility.
//
// Service for bulk EVM blockchain data operations
// Designed for high-throughput data extraction and analytics use cases
type BulkQueryServiceServer interface {
	// Get multiple blocks within a range in a single request
	GetBlocksByRange(context.Context, *GetBlocksByRangeRequest) (*GetBlocksByRangeResponse, error)
	mustEmbedUnimplementedBulkQueryServiceServer()
}

// UnimplementedBulkQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBulkQueryServiceServer struct{}

func (UnimplementedBulkQueryServiceServer) GetBlocksByRange(context.Context, *GetBlocksByRangeRequest) (*GetBlocksByRangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlocksByRange not implemented")
}
func (UnimplementedBulkQueryServiceServer) mustEmbedUnimplementedBulkQueryServiceServer() {}
func (UnimplementedBulkQueryServiceServer) testEmbeddedByValue()                          {}

// UnsafeBulkQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BulkQueryServiceServer will
// result in compilation errors.
type UnsafeBulkQueryServiceServer interface {
	mustEmbedUnimplementedBulkQueryServiceServer()
}

func RegisterBulkQueryServiceServer(s grpc.ServiceRegistrar, srv BulkQueryServiceServer) {
	// If the following call pancis, it indicates UnimplementedBulkQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BulkQueryService_ServiceDesc, srv)
}

func _BulkQueryService_GetBlocksByRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlocksByRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BulkQueryServiceServer).GetBlocksByRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BulkQueryService_GetBlocksByRange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BulkQueryServiceServer).GetBlocksByRange(ctx, req.(*GetBlocksByRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BulkQueryService_ServiceDesc is the grpc.ServiceDesc for BulkQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BulkQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bds.evm.BulkQueryService",
	HandlerType: (*BulkQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBlocksByRange",
			Handler:    _BulkQueryService_GetBlocksByRange_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bulk.proto",
}
