// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: query.proto

package evm

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	QueryService_QueryBlocks_FullMethodName       = "/bds.evm.QueryService/QueryBlocks"
	QueryService_QueryTransactions_FullMethodName = "/bds.evm.QueryService/QueryTransactions"
	QueryService_QueryLogs_FullMethodName         = "/bds.evm.QueryService/QueryLogs"
	QueryService_QueryTraces_FullMethodName       = "/bds.evm.QueryService/QueryTraces"
	QueryService_QueryTransfers_FullMethodName    = "/bds.evm.QueryService/QueryTransfers"
)

// QueryServiceClient is the client API for QueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryServiceClient interface {
	QueryBlocks(ctx context.Context, in *QueryBlocksRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryBlocksResponse], error)
	QueryTransactions(ctx context.Context, in *QueryTransactionsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryTransactionsResponse], error)
	QueryLogs(ctx context.Context, in *QueryLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryLogsResponse], error)
	QueryTraces(ctx context.Context, in *QueryTracesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryTracesResponse], error)
	QueryTransfers(ctx context.Context, in *QueryTransfersRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryTransfersResponse], error)
}

type queryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryServiceClient(cc grpc.ClientConnInterface) QueryServiceClient {
	return &queryServiceClient{cc}
}

func (c *queryServiceClient) QueryBlocks(ctx context.Context, in *QueryBlocksRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryBlocksResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &QueryService_ServiceDesc.Streams[0], QueryService_QueryBlocks_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[QueryBlocksRequest, QueryBlocksResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type QueryService_QueryBlocksClient = grpc.ServerStreamingClient[QueryBlocksResponse]

func (c *queryServiceClient) QueryTransactions(ctx context.Context, in *QueryTransactionsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryTransactionsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &QueryService_ServiceDesc.Streams[1], QueryService_QueryTransactions_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[QueryTransactionsRequest, QueryTransactionsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type QueryService_QueryTransactionsClient = grpc.ServerStreamingClient[QueryTransactionsResponse]

func (c *queryServiceClient) QueryLogs(ctx context.Context, in *QueryLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryLogsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &QueryService_ServiceDesc.Streams[2], QueryService_QueryLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[QueryLogsRequest, QueryLogsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type QueryService_QueryLogsClient = grpc.ServerStreamingClient[QueryLogsResponse]

func (c *queryServiceClient) QueryTraces(ctx context.Context, in *QueryTracesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryTracesResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &QueryService_ServiceDesc.Streams[3], QueryService_QueryTraces_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[QueryTracesRequest, QueryTracesResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type QueryService_QueryTracesClient = grpc.ServerStreamingClient[QueryTracesResponse]

func (c *queryServiceClient) QueryTransfers(ctx context.Context, in *QueryTransfersRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryTransfersResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &QueryService_ServiceDesc.Streams[4], QueryService_QueryTransfers_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[QueryTransfersRequest, QueryTransfersResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type QueryService_QueryTransfersClient = grpc.ServerStreamingClient[QueryTransfersResponse]

// QueryServiceServer is the server API for QueryService service.
// All implementations must embed UnimplementedQueryServiceServer
// for forward compatibility.
type QueryServiceServer interface {
	QueryBlocks(*QueryBlocksRequest, grpc.ServerStreamingServer[QueryBlocksResponse]) error
	QueryTransactions(*QueryTransactionsRequest, grpc.ServerStreamingServer[QueryTransactionsResponse]) error
	QueryLogs(*QueryLogsRequest, grpc.ServerStreamingServer[QueryLogsResponse]) error
	QueryTraces(*QueryTracesRequest, grpc.ServerStreamingServer[QueryTracesResponse]) error
	QueryTransfers(*QueryTransfersRequest, grpc.ServerStreamingServer[QueryTransfersResponse]) error
	mustEmbedUnimplementedQueryServiceServer()
}

// UnimplementedQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQueryServiceServer struct{}

func (UnimplementedQueryServiceServer) QueryBlocks(*QueryBlocksRequest, grpc.ServerStreamingServer[QueryBlocksResponse]) error {
	return status.Errorf(codes.Unimplemented, "method QueryBlocks not implemented")
}
func (UnimplementedQueryServiceServer) QueryTransactions(*QueryTransactionsRequest, grpc.ServerStreamingServer[QueryTransactionsResponse]) error {
	return status.Errorf(codes.Unimplemented, "method QueryTransactions not implemented")
}
func (UnimplementedQueryServiceServer) QueryLogs(*QueryLogsRequest, grpc.ServerStreamingServer[QueryLogsResponse]) error {
	return status.Errorf(codes.Unimplemented, "method QueryLogs not implemented")
}
func (UnimplementedQueryServiceServer) QueryTraces(*QueryTracesRequest, grpc.ServerStreamingServer[QueryTracesResponse]) error {
	return status.Errorf(codes.Unimplemented, "method QueryTraces not implemented")
}
func (UnimplementedQueryServiceServer) QueryTransfers(*QueryTransfersRequest, grpc.ServerStreamingServer[QueryTransfersResponse]) error {
	return status.Errorf(codes.Unimplemented, "method QueryTransfers not implemented")
}
func (UnimplementedQueryServiceServer) mustEmbedUnimplementedQueryServiceServer() {}
func (UnimplementedQueryServiceServer) testEmbeddedByValue()                      {}

// UnsafeQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServiceServer will
// result in compilation errors.
type UnsafeQueryServiceServer interface {
	mustEmbedUnimplementedQueryServiceServer()
}

func RegisterQueryServiceServer(s grpc.ServiceRegistrar, srv QueryServiceServer) {
	// If the following call pancis, it indicates UnimplementedQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QueryService_ServiceDesc, srv)
}

func _QueryService_QueryBlocks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(QueryBlocksRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(QueryServiceServer).QueryBlocks(m, &grpc.GenericServerStream[QueryBlocksRequest, QueryBlocksResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type QueryService_QueryBlocksServer = grpc.ServerStreamingServer[QueryBlocksResponse]

func _QueryService_QueryTransactions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(QueryTransactionsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(QueryServiceServer).QueryTransactions(m, &grpc.GenericServerStream[QueryTransactionsRequest, QueryTransactionsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type QueryService_QueryTransactionsServer = grpc.ServerStreamingServer[QueryTransactionsResponse]

func _QueryService_QueryLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(QueryLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(QueryServiceServer).QueryLogs(m, &grpc.GenericServerStream[QueryLogsRequest, QueryLogsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type QueryService_QueryLogsServer = grpc.ServerStreamingServer[QueryLogsResponse]

func _QueryService_QueryTraces_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(QueryTracesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(QueryServiceServer).QueryTraces(m, &grpc.GenericServerStream[QueryTracesRequest, QueryTracesResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type QueryService_QueryTracesServer = grpc.ServerStreamingServer[QueryTracesResponse]

func _QueryService_QueryTransfers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(QueryTransfersRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(QueryServiceServer).QueryTransfers(m, &grpc.GenericServerStream[QueryTransfersRequest, QueryTransfersResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type QueryService_QueryTransfersServer = grpc.ServerStreamingServer[QueryTransfersResponse]

// QueryService_ServiceDesc is the grpc.ServiceDesc for QueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bds.evm.QueryService",
	HandlerType: (*QueryServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "QueryBlocks",
			Handler:       _QueryService_QueryBlocks_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "QueryTransactions",
			Handler:       _QueryService_QueryTransactions_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "QueryLogs",
			Handler:       _QueryService_QueryLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "QueryTraces",
			Handler:       _QueryService_QueryTraces_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "QueryTransfers",
			Handler:       _QueryService_QueryTransfers_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "query.proto",
}
