// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: query.proto

package evm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SortOrder int32

const (
	SortOrder_ASC  SortOrder = 0
	SortOrder_DESC SortOrder = 1
)

// Enum value maps for SortOrder.
var (
	SortOrder_name = map[int32]string{
		0: "ASC",
		1: "DESC",
	}
	SortOrder_value = map[string]int32{
		"ASC":  0,
		"DESC": 1,
	}
)

func (x SortOrder) Enum() *SortOrder {
	p := new(SortOrder)
	*p = x
	return p
}

func (x SortOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_query_proto_enumTypes[0].Descriptor()
}

func (SortOrder) Type() protoreflect.EnumType {
	return &file_query_proto_enumTypes[0]
}

func (x SortOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortOrder.Descriptor instead.
func (SortOrder) EnumDescriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{0}
}

type CursorBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        uint64                 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Hash          []byte                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	ParentHash    []byte                 `protobuf:"bytes,3,opt,name=parentHash,proto3" json:"parentHash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CursorBlock) Reset() {
	*x = CursorBlock{}
	mi := &file_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CursorBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CursorBlock) ProtoMessage() {}

func (x *CursorBlock) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CursorBlock.ProtoReflect.Descriptor instead.
func (*CursorBlock) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{0}
}

func (x *CursorBlock) GetNumber() uint64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *CursorBlock) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *CursorBlock) GetParentHash() []byte {
	if x != nil {
		return x.ParentHash
	}
	return nil
}

type BlockFieldSelection struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Number                bool                   `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Timestamp             bool                   `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Hash                  bool                   `protobuf:"varint,3,opt,name=hash,proto3" json:"hash,omitempty"`
	ParentHash            bool                   `protobuf:"varint,4,opt,name=parentHash,proto3" json:"parentHash,omitempty"`
	StateRoot             bool                   `protobuf:"varint,5,opt,name=stateRoot,proto3" json:"stateRoot,omitempty"`
	TransactionsRoot      bool                   `protobuf:"varint,6,opt,name=transactionsRoot,proto3" json:"transactionsRoot,omitempty"`
	ReceiptsRoot          bool                   `protobuf:"varint,7,opt,name=receiptsRoot,proto3" json:"receiptsRoot,omitempty"`
	LogsBloom             bool                   `protobuf:"varint,8,opt,name=logsBloom,proto3" json:"logsBloom,omitempty"`
	GasLimit              bool                   `protobuf:"varint,9,opt,name=gasLimit,proto3" json:"gasLimit,omitempty"`
	GasUsed               bool                   `protobuf:"varint,10,opt,name=gasUsed,proto3" json:"gasUsed,omitempty"`
	Miner                 bool                   `protobuf:"varint,11,opt,name=miner,proto3" json:"miner,omitempty"`
	ExtraData             bool                   `protobuf:"varint,12,opt,name=extraData,proto3" json:"extraData,omitempty"`
	Size                  bool                   `protobuf:"varint,13,opt,name=size,proto3" json:"size,omitempty"`
	Sha3Uncles            bool                   `protobuf:"varint,14,opt,name=sha3Uncles,proto3" json:"sha3Uncles,omitempty"`
	Nonce                 bool                   `protobuf:"varint,15,opt,name=nonce,proto3" json:"nonce,omitempty"`
	BaseFeePerGas         bool                   `protobuf:"varint,16,opt,name=baseFeePerGas,proto3" json:"baseFeePerGas,omitempty"`
	Difficulty            bool                   `protobuf:"varint,17,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	TotalDifficulty       bool                   `protobuf:"varint,18,opt,name=totalDifficulty,proto3" json:"totalDifficulty,omitempty"`
	MixHash               bool                   `protobuf:"varint,19,opt,name=mixHash,proto3" json:"mixHash,omitempty"`
	BlobGasUsed           bool                   `protobuf:"varint,20,opt,name=blobGasUsed,proto3" json:"blobGasUsed,omitempty"`
	ExcessBlobGas         bool                   `protobuf:"varint,21,opt,name=excessBlobGas,proto3" json:"excessBlobGas,omitempty"`
	WithdrawalsRoot       bool                   `protobuf:"varint,22,opt,name=withdrawalsRoot,proto3" json:"withdrawalsRoot,omitempty"`
	ParentBeaconBlockRoot bool                   `protobuf:"varint,23,opt,name=parentBeaconBlockRoot,proto3" json:"parentBeaconBlockRoot,omitempty"`
	TransactionCount      bool                   `protobuf:"varint,24,opt,name=transactionCount,proto3" json:"transactionCount,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *BlockFieldSelection) Reset() {
	*x = BlockFieldSelection{}
	mi := &file_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockFieldSelection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockFieldSelection) ProtoMessage() {}

func (x *BlockFieldSelection) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockFieldSelection.ProtoReflect.Descriptor instead.
func (*BlockFieldSelection) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{1}
}

func (x *BlockFieldSelection) GetNumber() bool {
	if x != nil {
		return x.Number
	}
	return false
}

func (x *BlockFieldSelection) GetTimestamp() bool {
	if x != nil {
		return x.Timestamp
	}
	return false
}

func (x *BlockFieldSelection) GetHash() bool {
	if x != nil {
		return x.Hash
	}
	return false
}

func (x *BlockFieldSelection) GetParentHash() bool {
	if x != nil {
		return x.ParentHash
	}
	return false
}

func (x *BlockFieldSelection) GetStateRoot() bool {
	if x != nil {
		return x.StateRoot
	}
	return false
}

func (x *BlockFieldSelection) GetTransactionsRoot() bool {
	if x != nil {
		return x.TransactionsRoot
	}
	return false
}

func (x *BlockFieldSelection) GetReceiptsRoot() bool {
	if x != nil {
		return x.ReceiptsRoot
	}
	return false
}

func (x *BlockFieldSelection) GetLogsBloom() bool {
	if x != nil {
		return x.LogsBloom
	}
	return false
}

func (x *BlockFieldSelection) GetGasLimit() bool {
	if x != nil {
		return x.GasLimit
	}
	return false
}

func (x *BlockFieldSelection) GetGasUsed() bool {
	if x != nil {
		return x.GasUsed
	}
	return false
}

func (x *BlockFieldSelection) GetMiner() bool {
	if x != nil {
		return x.Miner
	}
	return false
}

func (x *BlockFieldSelection) GetExtraData() bool {
	if x != nil {
		return x.ExtraData
	}
	return false
}

func (x *BlockFieldSelection) GetSize() bool {
	if x != nil {
		return x.Size
	}
	return false
}

func (x *BlockFieldSelection) GetSha3Uncles() bool {
	if x != nil {
		return x.Sha3Uncles
	}
	return false
}

func (x *BlockFieldSelection) GetNonce() bool {
	if x != nil {
		return x.Nonce
	}
	return false
}

func (x *BlockFieldSelection) GetBaseFeePerGas() bool {
	if x != nil {
		return x.BaseFeePerGas
	}
	return false
}

func (x *BlockFieldSelection) GetDifficulty() bool {
	if x != nil {
		return x.Difficulty
	}
	return false
}

func (x *BlockFieldSelection) GetTotalDifficulty() bool {
	if x != nil {
		return x.TotalDifficulty
	}
	return false
}

func (x *BlockFieldSelection) GetMixHash() bool {
	if x != nil {
		return x.MixHash
	}
	return false
}

func (x *BlockFieldSelection) GetBlobGasUsed() bool {
	if x != nil {
		return x.BlobGasUsed
	}
	return false
}

func (x *BlockFieldSelection) GetExcessBlobGas() bool {
	if x != nil {
		return x.ExcessBlobGas
	}
	return false
}

func (x *BlockFieldSelection) GetWithdrawalsRoot() bool {
	if x != nil {
		return x.WithdrawalsRoot
	}
	return false
}

func (x *BlockFieldSelection) GetParentBeaconBlockRoot() bool {
	if x != nil {
		return x.ParentBeaconBlockRoot
	}
	return false
}

func (x *BlockFieldSelection) GetTransactionCount() bool {
	if x != nil {
		return x.TransactionCount
	}
	return false
}

type TransactionFieldSelection struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Hash                 bool                   `protobuf:"varint,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Nonce                bool                   `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	From                 bool                   `protobuf:"varint,3,opt,name=from,proto3" json:"from,omitempty"`
	To                   bool                   `protobuf:"varint,4,opt,name=to,proto3" json:"to,omitempty"`
	Value                bool                   `protobuf:"varint,5,opt,name=value,proto3" json:"value,omitempty"`
	Input                bool                   `protobuf:"varint,6,opt,name=input,proto3" json:"input,omitempty"`
	Type                 bool                   `protobuf:"varint,7,opt,name=type,proto3" json:"type,omitempty"`
	GasLimit             bool                   `protobuf:"varint,8,opt,name=gasLimit,proto3" json:"gasLimit,omitempty"`
	GasPrice             bool                   `protobuf:"varint,9,opt,name=gasPrice,proto3" json:"gasPrice,omitempty"`
	MaxFeePerGas         bool                   `protobuf:"varint,10,opt,name=maxFeePerGas,proto3" json:"maxFeePerGas,omitempty"`
	MaxPriorityFeePerGas bool                   `protobuf:"varint,11,opt,name=maxPriorityFeePerGas,proto3" json:"maxPriorityFeePerGas,omitempty"`
	GasUsed              bool                   `protobuf:"varint,12,opt,name=gasUsed,proto3" json:"gasUsed,omitempty"`
	EffectiveGasPrice    bool                   `protobuf:"varint,13,opt,name=effectiveGasPrice,proto3" json:"effectiveGasPrice,omitempty"`
	BlockNumber          bool                   `protobuf:"varint,14,opt,name=blockNumber,proto3" json:"blockNumber,omitempty"`
	BlockHash            bool                   `protobuf:"varint,15,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	TransactionIndex     bool                   `protobuf:"varint,16,opt,name=transactionIndex,proto3" json:"transactionIndex,omitempty"`
	BlockTimestamp       bool                   `protobuf:"varint,17,opt,name=blockTimestamp,proto3" json:"blockTimestamp,omitempty"`
	ChainId              bool                   `protobuf:"varint,18,opt,name=chainId,proto3" json:"chainId,omitempty"`
	AccessList           bool                   `protobuf:"varint,19,opt,name=accessList,proto3" json:"accessList,omitempty"`
	MaxFeePerBlobGas     bool                   `protobuf:"varint,20,opt,name=maxFeePerBlobGas,proto3" json:"maxFeePerBlobGas,omitempty"`
	BlobVersionedHashes  bool                   `protobuf:"varint,21,opt,name=blobVersionedHashes,proto3" json:"blobVersionedHashes,omitempty"`
	R                    bool                   `protobuf:"varint,22,opt,name=r,proto3" json:"r,omitempty"`
	S                    bool                   `protobuf:"varint,23,opt,name=s,proto3" json:"s,omitempty"`
	V                    bool                   `protobuf:"varint,24,opt,name=v,proto3" json:"v,omitempty"`
	YParity              bool                   `protobuf:"varint,25,opt,name=yParity,proto3" json:"yParity,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TransactionFieldSelection) Reset() {
	*x = TransactionFieldSelection{}
	mi := &file_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionFieldSelection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionFieldSelection) ProtoMessage() {}

func (x *TransactionFieldSelection) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionFieldSelection.ProtoReflect.Descriptor instead.
func (*TransactionFieldSelection) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{2}
}

func (x *TransactionFieldSelection) GetHash() bool {
	if x != nil {
		return x.Hash
	}
	return false
}

func (x *TransactionFieldSelection) GetNonce() bool {
	if x != nil {
		return x.Nonce
	}
	return false
}

func (x *TransactionFieldSelection) GetFrom() bool {
	if x != nil {
		return x.From
	}
	return false
}

func (x *TransactionFieldSelection) GetTo() bool {
	if x != nil {
		return x.To
	}
	return false
}

func (x *TransactionFieldSelection) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

func (x *TransactionFieldSelection) GetInput() bool {
	if x != nil {
		return x.Input
	}
	return false
}

func (x *TransactionFieldSelection) GetType() bool {
	if x != nil {
		return x.Type
	}
	return false
}

func (x *TransactionFieldSelection) GetGasLimit() bool {
	if x != nil {
		return x.GasLimit
	}
	return false
}

func (x *TransactionFieldSelection) GetGasPrice() bool {
	if x != nil {
		return x.GasPrice
	}
	return false
}

func (x *TransactionFieldSelection) GetMaxFeePerGas() bool {
	if x != nil {
		return x.MaxFeePerGas
	}
	return false
}

func (x *TransactionFieldSelection) GetMaxPriorityFeePerGas() bool {
	if x != nil {
		return x.MaxPriorityFeePerGas
	}
	return false
}

func (x *TransactionFieldSelection) GetGasUsed() bool {
	if x != nil {
		return x.GasUsed
	}
	return false
}

func (x *TransactionFieldSelection) GetEffectiveGasPrice() bool {
	if x != nil {
		return x.EffectiveGasPrice
	}
	return false
}

func (x *TransactionFieldSelection) GetBlockNumber() bool {
	if x != nil {
		return x.BlockNumber
	}
	return false
}

func (x *TransactionFieldSelection) GetBlockHash() bool {
	if x != nil {
		return x.BlockHash
	}
	return false
}

func (x *TransactionFieldSelection) GetTransactionIndex() bool {
	if x != nil {
		return x.TransactionIndex
	}
	return false
}

func (x *TransactionFieldSelection) GetBlockTimestamp() bool {
	if x != nil {
		return x.BlockTimestamp
	}
	return false
}

func (x *TransactionFieldSelection) GetChainId() bool {
	if x != nil {
		return x.ChainId
	}
	return false
}

func (x *TransactionFieldSelection) GetAccessList() bool {
	if x != nil {
		return x.AccessList
	}
	return false
}

func (x *TransactionFieldSelection) GetMaxFeePerBlobGas() bool {
	if x != nil {
		return x.MaxFeePerBlobGas
	}
	return false
}

func (x *TransactionFieldSelection) GetBlobVersionedHashes() bool {
	if x != nil {
		return x.BlobVersionedHashes
	}
	return false
}

func (x *TransactionFieldSelection) GetR() bool {
	if x != nil {
		return x.R
	}
	return false
}

func (x *TransactionFieldSelection) GetS() bool {
	if x != nil {
		return x.S
	}
	return false
}

func (x *TransactionFieldSelection) GetV() bool {
	if x != nil {
		return x.V
	}
	return false
}

func (x *TransactionFieldSelection) GetYParity() bool {
	if x != nil {
		return x.YParity
	}
	return false
}

type LogFieldSelection struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Address          bool                   `protobuf:"varint,1,opt,name=address,proto3" json:"address,omitempty"`
	Topics           bool                   `protobuf:"varint,2,opt,name=topics,proto3" json:"topics,omitempty"`
	Data             bool                   `protobuf:"varint,3,opt,name=data,proto3" json:"data,omitempty"`
	BlockNumber      bool                   `protobuf:"varint,4,opt,name=blockNumber,proto3" json:"blockNumber,omitempty"`
	BlockHash        bool                   `protobuf:"varint,5,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	TransactionHash  bool                   `protobuf:"varint,6,opt,name=transactionHash,proto3" json:"transactionHash,omitempty"`
	TransactionIndex bool                   `protobuf:"varint,7,opt,name=transactionIndex,proto3" json:"transactionIndex,omitempty"`
	LogIndex         bool                   `protobuf:"varint,8,opt,name=logIndex,proto3" json:"logIndex,omitempty"`
	BlockTimestamp   bool                   `protobuf:"varint,9,opt,name=blockTimestamp,proto3" json:"blockTimestamp,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LogFieldSelection) Reset() {
	*x = LogFieldSelection{}
	mi := &file_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogFieldSelection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogFieldSelection) ProtoMessage() {}

func (x *LogFieldSelection) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogFieldSelection.ProtoReflect.Descriptor instead.
func (*LogFieldSelection) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{3}
}

func (x *LogFieldSelection) GetAddress() bool {
	if x != nil {
		return x.Address
	}
	return false
}

func (x *LogFieldSelection) GetTopics() bool {
	if x != nil {
		return x.Topics
	}
	return false
}

func (x *LogFieldSelection) GetData() bool {
	if x != nil {
		return x.Data
	}
	return false
}

func (x *LogFieldSelection) GetBlockNumber() bool {
	if x != nil {
		return x.BlockNumber
	}
	return false
}

func (x *LogFieldSelection) GetBlockHash() bool {
	if x != nil {
		return x.BlockHash
	}
	return false
}

func (x *LogFieldSelection) GetTransactionHash() bool {
	if x != nil {
		return x.TransactionHash
	}
	return false
}

func (x *LogFieldSelection) GetTransactionIndex() bool {
	if x != nil {
		return x.TransactionIndex
	}
	return false
}

func (x *LogFieldSelection) GetLogIndex() bool {
	if x != nil {
		return x.LogIndex
	}
	return false
}

func (x *LogFieldSelection) GetBlockTimestamp() bool {
	if x != nil {
		return x.BlockTimestamp
	}
	return false
}

type TraceFieldSelection struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TraceType        bool                   `protobuf:"varint,1,opt,name=traceType,proto3" json:"traceType,omitempty"`
	CallType         bool                   `protobuf:"varint,2,opt,name=callType,proto3" json:"callType,omitempty"`
	From             bool                   `protobuf:"varint,3,opt,name=from,proto3" json:"from,omitempty"`
	To               bool                   `protobuf:"varint,4,opt,name=to,proto3" json:"to,omitempty"`
	Value            bool                   `protobuf:"varint,5,opt,name=value,proto3" json:"value,omitempty"`
	Input            bool                   `protobuf:"varint,6,opt,name=input,proto3" json:"input,omitempty"`
	Output           bool                   `protobuf:"varint,7,opt,name=output,proto3" json:"output,omitempty"`
	Gas              bool                   `protobuf:"varint,8,opt,name=gas,proto3" json:"gas,omitempty"`
	GasUsed          bool                   `protobuf:"varint,9,opt,name=gasUsed,proto3" json:"gasUsed,omitempty"`
	Error            bool                   `protobuf:"varint,10,opt,name=error,proto3" json:"error,omitempty"`
	Subtraces        bool                   `protobuf:"varint,11,opt,name=subtraces,proto3" json:"subtraces,omitempty"`
	TraceAddress     bool                   `protobuf:"varint,12,opt,name=traceAddress,proto3" json:"traceAddress,omitempty"`
	TransactionHash  bool                   `protobuf:"varint,13,opt,name=transactionHash,proto3" json:"transactionHash,omitempty"`
	TransactionIndex bool                   `protobuf:"varint,14,opt,name=transactionIndex,proto3" json:"transactionIndex,omitempty"`
	BlockNumber      bool                   `protobuf:"varint,15,opt,name=blockNumber,proto3" json:"blockNumber,omitempty"`
	BlockHash        bool                   `protobuf:"varint,16,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	BlockTimestamp   bool                   `protobuf:"varint,17,opt,name=blockTimestamp,proto3" json:"blockTimestamp,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TraceFieldSelection) Reset() {
	*x = TraceFieldSelection{}
	mi := &file_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceFieldSelection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceFieldSelection) ProtoMessage() {}

func (x *TraceFieldSelection) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceFieldSelection.ProtoReflect.Descriptor instead.
func (*TraceFieldSelection) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{4}
}

func (x *TraceFieldSelection) GetTraceType() bool {
	if x != nil {
		return x.TraceType
	}
	return false
}

func (x *TraceFieldSelection) GetCallType() bool {
	if x != nil {
		return x.CallType
	}
	return false
}

func (x *TraceFieldSelection) GetFrom() bool {
	if x != nil {
		return x.From
	}
	return false
}

func (x *TraceFieldSelection) GetTo() bool {
	if x != nil {
		return x.To
	}
	return false
}

func (x *TraceFieldSelection) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

func (x *TraceFieldSelection) GetInput() bool {
	if x != nil {
		return x.Input
	}
	return false
}

func (x *TraceFieldSelection) GetOutput() bool {
	if x != nil {
		return x.Output
	}
	return false
}

func (x *TraceFieldSelection) GetGas() bool {
	if x != nil {
		return x.Gas
	}
	return false
}

func (x *TraceFieldSelection) GetGasUsed() bool {
	if x != nil {
		return x.GasUsed
	}
	return false
}

func (x *TraceFieldSelection) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *TraceFieldSelection) GetSubtraces() bool {
	if x != nil {
		return x.Subtraces
	}
	return false
}

func (x *TraceFieldSelection) GetTraceAddress() bool {
	if x != nil {
		return x.TraceAddress
	}
	return false
}

func (x *TraceFieldSelection) GetTransactionHash() bool {
	if x != nil {
		return x.TransactionHash
	}
	return false
}

func (x *TraceFieldSelection) GetTransactionIndex() bool {
	if x != nil {
		return x.TransactionIndex
	}
	return false
}

func (x *TraceFieldSelection) GetBlockNumber() bool {
	if x != nil {
		return x.BlockNumber
	}
	return false
}

func (x *TraceFieldSelection) GetBlockHash() bool {
	if x != nil {
		return x.BlockHash
	}
	return false
}

func (x *TraceFieldSelection) GetBlockTimestamp() bool {
	if x != nil {
		return x.BlockTimestamp
	}
	return false
}

type TransferFieldSelection struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	From             bool                   `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	To               bool                   `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	Value            bool                   `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	TransactionHash  bool                   `protobuf:"varint,4,opt,name=transactionHash,proto3" json:"transactionHash,omitempty"`
	TransactionIndex bool                   `protobuf:"varint,5,opt,name=transactionIndex,proto3" json:"transactionIndex,omitempty"`
	BlockNumber      bool                   `protobuf:"varint,6,opt,name=blockNumber,proto3" json:"blockNumber,omitempty"`
	BlockHash        bool                   `protobuf:"varint,7,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	TraceAddress     bool                   `protobuf:"varint,8,opt,name=traceAddress,proto3" json:"traceAddress,omitempty"`
	BlockTimestamp   bool                   `protobuf:"varint,9,opt,name=blockTimestamp,proto3" json:"blockTimestamp,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TransferFieldSelection) Reset() {
	*x = TransferFieldSelection{}
	mi := &file_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferFieldSelection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferFieldSelection) ProtoMessage() {}

func (x *TransferFieldSelection) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferFieldSelection.ProtoReflect.Descriptor instead.
func (*TransferFieldSelection) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{5}
}

func (x *TransferFieldSelection) GetFrom() bool {
	if x != nil {
		return x.From
	}
	return false
}

func (x *TransferFieldSelection) GetTo() bool {
	if x != nil {
		return x.To
	}
	return false
}

func (x *TransferFieldSelection) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

func (x *TransferFieldSelection) GetTransactionHash() bool {
	if x != nil {
		return x.TransactionHash
	}
	return false
}

func (x *TransferFieldSelection) GetTransactionIndex() bool {
	if x != nil {
		return x.TransactionIndex
	}
	return false
}

func (x *TransferFieldSelection) GetBlockNumber() bool {
	if x != nil {
		return x.BlockNumber
	}
	return false
}

func (x *TransferFieldSelection) GetBlockHash() bool {
	if x != nil {
		return x.BlockHash
	}
	return false
}

func (x *TransferFieldSelection) GetTraceAddress() bool {
	if x != nil {
		return x.TraceAddress
	}
	return false
}

func (x *TransferFieldSelection) GetBlockTimestamp() bool {
	if x != nil {
		return x.BlockTimestamp
	}
	return false
}

type TransactionFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          [][]byte               `protobuf:"bytes,1,rep,name=from,proto3" json:"from,omitempty"`
	To            [][]byte               `protobuf:"bytes,2,rep,name=to,proto3" json:"to,omitempty"`
	Selector      [][]byte               `protobuf:"bytes,3,rep,name=selector,proto3" json:"selector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionFilter) Reset() {
	*x = TransactionFilter{}
	mi := &file_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionFilter) ProtoMessage() {}

func (x *TransactionFilter) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionFilter.ProtoReflect.Descriptor instead.
func (*TransactionFilter) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{6}
}

func (x *TransactionFilter) GetFrom() [][]byte {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *TransactionFilter) GetTo() [][]byte {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *TransactionFilter) GetSelector() [][]byte {
	if x != nil {
		return x.Selector
	}
	return nil
}

type LogFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       [][]byte               `protobuf:"bytes,1,rep,name=address,proto3" json:"address,omitempty"`
	Topics        []*TopicFilter         `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogFilter) Reset() {
	*x = LogFilter{}
	mi := &file_query_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogFilter) ProtoMessage() {}

func (x *LogFilter) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogFilter.ProtoReflect.Descriptor instead.
func (*LogFilter) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{7}
}

func (x *LogFilter) GetAddress() [][]byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *LogFilter) GetTopics() []*TopicFilter {
	if x != nil {
		return x.Topics
	}
	return nil
}

type TraceFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          [][]byte               `protobuf:"bytes,1,rep,name=from,proto3" json:"from,omitempty"`
	To            [][]byte               `protobuf:"bytes,2,rep,name=to,proto3" json:"to,omitempty"`
	Selector      [][]byte               `protobuf:"bytes,3,rep,name=selector,proto3" json:"selector,omitempty"`
	IsTopLevel    *bool                  `protobuf:"varint,4,opt,name=isTopLevel,proto3,oneof" json:"isTopLevel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceFilter) Reset() {
	*x = TraceFilter{}
	mi := &file_query_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceFilter) ProtoMessage() {}

func (x *TraceFilter) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceFilter.ProtoReflect.Descriptor instead.
func (*TraceFilter) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{8}
}

func (x *TraceFilter) GetFrom() [][]byte {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *TraceFilter) GetTo() [][]byte {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *TraceFilter) GetSelector() [][]byte {
	if x != nil {
		return x.Selector
	}
	return nil
}

func (x *TraceFilter) GetIsTopLevel() bool {
	if x != nil && x.IsTopLevel != nil {
		return *x.IsTopLevel
	}
	return false
}

type TransferFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          [][]byte               `protobuf:"bytes,1,rep,name=from,proto3" json:"from,omitempty"`
	To            [][]byte               `protobuf:"bytes,2,rep,name=to,proto3" json:"to,omitempty"`
	IsTopLevel    *bool                  `protobuf:"varint,3,opt,name=isTopLevel,proto3,oneof" json:"isTopLevel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferFilter) Reset() {
	*x = TransferFilter{}
	mi := &file_query_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferFilter) ProtoMessage() {}

func (x *TransferFilter) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferFilter.ProtoReflect.Descriptor instead.
func (*TransferFilter) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{9}
}

func (x *TransferFilter) GetFrom() [][]byte {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *TransferFilter) GetTo() [][]byte {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *TransferFilter) GetIsTopLevel() bool {
	if x != nil && x.IsTopLevel != nil {
		return *x.IsTopLevel
	}
	return false
}

type QueryBlocksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromBlock     *string                `protobuf:"bytes,1,opt,name=fromBlock,proto3,oneof" json:"fromBlock,omitempty"`
	ToBlock       *string                `protobuf:"bytes,2,opt,name=toBlock,proto3,oneof" json:"toBlock,omitempty"`
	Order         *SortOrder             `protobuf:"varint,3,opt,name=order,proto3,enum=bds.evm.SortOrder,oneof" json:"order,omitempty"`
	Limit         *uint32                `protobuf:"varint,4,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Cursor        *CursorBlock           `protobuf:"bytes,5,opt,name=cursor,proto3,oneof" json:"cursor,omitempty"`
	ChainId       *uint64                `protobuf:"varint,6,opt,name=chainId,proto3,oneof" json:"chainId,omitempty"`
	BlockFields   *BlockFieldSelection   `protobuf:"bytes,10,opt,name=blockFields,proto3" json:"blockFields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryBlocksRequest) Reset() {
	*x = QueryBlocksRequest{}
	mi := &file_query_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryBlocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryBlocksRequest) ProtoMessage() {}

func (x *QueryBlocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryBlocksRequest.ProtoReflect.Descriptor instead.
func (*QueryBlocksRequest) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{10}
}

func (x *QueryBlocksRequest) GetFromBlock() string {
	if x != nil && x.FromBlock != nil {
		return *x.FromBlock
	}
	return ""
}

func (x *QueryBlocksRequest) GetToBlock() string {
	if x != nil && x.ToBlock != nil {
		return *x.ToBlock
	}
	return ""
}

func (x *QueryBlocksRequest) GetOrder() SortOrder {
	if x != nil && x.Order != nil {
		return *x.Order
	}
	return SortOrder_ASC
}

func (x *QueryBlocksRequest) GetLimit() uint32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *QueryBlocksRequest) GetCursor() *CursorBlock {
	if x != nil {
		return x.Cursor
	}
	return nil
}

func (x *QueryBlocksRequest) GetChainId() uint64 {
	if x != nil && x.ChainId != nil {
		return *x.ChainId
	}
	return 0
}

func (x *QueryBlocksRequest) GetBlockFields() *BlockFieldSelection {
	if x != nil {
		return x.BlockFields
	}
	return nil
}

type QueryTransactionsRequest struct {
	state             protoimpl.MessageState     `protogen:"open.v1"`
	FromBlock         *string                    `protobuf:"bytes,1,opt,name=fromBlock,proto3,oneof" json:"fromBlock,omitempty"`
	ToBlock           *string                    `protobuf:"bytes,2,opt,name=toBlock,proto3,oneof" json:"toBlock,omitempty"`
	Order             *SortOrder                 `protobuf:"varint,3,opt,name=order,proto3,enum=bds.evm.SortOrder,oneof" json:"order,omitempty"`
	Limit             *uint32                    `protobuf:"varint,4,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Cursor            *CursorBlock               `protobuf:"bytes,5,opt,name=cursor,proto3,oneof" json:"cursor,omitempty"`
	ChainId           *uint64                    `protobuf:"varint,6,opt,name=chainId,proto3,oneof" json:"chainId,omitempty"`
	Filter            *TransactionFilter         `protobuf:"bytes,10,opt,name=filter,proto3" json:"filter,omitempty"`
	TransactionFields *TransactionFieldSelection `protobuf:"bytes,11,opt,name=transactionFields,proto3" json:"transactionFields,omitempty"`
	BlockFields       *BlockFieldSelection       `protobuf:"bytes,12,opt,name=blockFields,proto3" json:"blockFields,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *QueryTransactionsRequest) Reset() {
	*x = QueryTransactionsRequest{}
	mi := &file_query_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTransactionsRequest) ProtoMessage() {}

func (x *QueryTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTransactionsRequest.ProtoReflect.Descriptor instead.
func (*QueryTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{11}
}

func (x *QueryTransactionsRequest) GetFromBlock() string {
	if x != nil && x.FromBlock != nil {
		return *x.FromBlock
	}
	return ""
}

func (x *QueryTransactionsRequest) GetToBlock() string {
	if x != nil && x.ToBlock != nil {
		return *x.ToBlock
	}
	return ""
}

func (x *QueryTransactionsRequest) GetOrder() SortOrder {
	if x != nil && x.Order != nil {
		return *x.Order
	}
	return SortOrder_ASC
}

func (x *QueryTransactionsRequest) GetLimit() uint32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *QueryTransactionsRequest) GetCursor() *CursorBlock {
	if x != nil {
		return x.Cursor
	}
	return nil
}

func (x *QueryTransactionsRequest) GetChainId() uint64 {
	if x != nil && x.ChainId != nil {
		return *x.ChainId
	}
	return 0
}

func (x *QueryTransactionsRequest) GetFilter() *TransactionFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *QueryTransactionsRequest) GetTransactionFields() *TransactionFieldSelection {
	if x != nil {
		return x.TransactionFields
	}
	return nil
}

func (x *QueryTransactionsRequest) GetBlockFields() *BlockFieldSelection {
	if x != nil {
		return x.BlockFields
	}
	return nil
}

type QueryLogsRequest struct {
	state             protoimpl.MessageState     `protogen:"open.v1"`
	FromBlock         *string                    `protobuf:"bytes,1,opt,name=fromBlock,proto3,oneof" json:"fromBlock,omitempty"`
	ToBlock           *string                    `protobuf:"bytes,2,opt,name=toBlock,proto3,oneof" json:"toBlock,omitempty"`
	Order             *SortOrder                 `protobuf:"varint,3,opt,name=order,proto3,enum=bds.evm.SortOrder,oneof" json:"order,omitempty"`
	Limit             *uint32                    `protobuf:"varint,4,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Cursor            *CursorBlock               `protobuf:"bytes,5,opt,name=cursor,proto3,oneof" json:"cursor,omitempty"`
	ChainId           *uint64                    `protobuf:"varint,6,opt,name=chainId,proto3,oneof" json:"chainId,omitempty"`
	Filter            *LogFilter                 `protobuf:"bytes,10,opt,name=filter,proto3" json:"filter,omitempty"`
	LogFields         *LogFieldSelection         `protobuf:"bytes,11,opt,name=logFields,proto3" json:"logFields,omitempty"`
	TransactionFields *TransactionFieldSelection `protobuf:"bytes,12,opt,name=transactionFields,proto3" json:"transactionFields,omitempty"`
	BlockFields       *BlockFieldSelection       `protobuf:"bytes,13,opt,name=blockFields,proto3" json:"blockFields,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *QueryLogsRequest) Reset() {
	*x = QueryLogsRequest{}
	mi := &file_query_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLogsRequest) ProtoMessage() {}

func (x *QueryLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLogsRequest.ProtoReflect.Descriptor instead.
func (*QueryLogsRequest) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{12}
}

func (x *QueryLogsRequest) GetFromBlock() string {
	if x != nil && x.FromBlock != nil {
		return *x.FromBlock
	}
	return ""
}

func (x *QueryLogsRequest) GetToBlock() string {
	if x != nil && x.ToBlock != nil {
		return *x.ToBlock
	}
	return ""
}

func (x *QueryLogsRequest) GetOrder() SortOrder {
	if x != nil && x.Order != nil {
		return *x.Order
	}
	return SortOrder_ASC
}

func (x *QueryLogsRequest) GetLimit() uint32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *QueryLogsRequest) GetCursor() *CursorBlock {
	if x != nil {
		return x.Cursor
	}
	return nil
}

func (x *QueryLogsRequest) GetChainId() uint64 {
	if x != nil && x.ChainId != nil {
		return *x.ChainId
	}
	return 0
}

func (x *QueryLogsRequest) GetFilter() *LogFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *QueryLogsRequest) GetLogFields() *LogFieldSelection {
	if x != nil {
		return x.LogFields
	}
	return nil
}

func (x *QueryLogsRequest) GetTransactionFields() *TransactionFieldSelection {
	if x != nil {
		return x.TransactionFields
	}
	return nil
}

func (x *QueryLogsRequest) GetBlockFields() *BlockFieldSelection {
	if x != nil {
		return x.BlockFields
	}
	return nil
}

type QueryTracesRequest struct {
	state             protoimpl.MessageState     `protogen:"open.v1"`
	FromBlock         *string                    `protobuf:"bytes,1,opt,name=fromBlock,proto3,oneof" json:"fromBlock,omitempty"`
	ToBlock           *string                    `protobuf:"bytes,2,opt,name=toBlock,proto3,oneof" json:"toBlock,omitempty"`
	Order             *SortOrder                 `protobuf:"varint,3,opt,name=order,proto3,enum=bds.evm.SortOrder,oneof" json:"order,omitempty"`
	Limit             *uint32                    `protobuf:"varint,4,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Cursor            *CursorBlock               `protobuf:"bytes,5,opt,name=cursor,proto3,oneof" json:"cursor,omitempty"`
	ChainId           *uint64                    `protobuf:"varint,6,opt,name=chainId,proto3,oneof" json:"chainId,omitempty"`
	Filter            *TraceFilter               `protobuf:"bytes,10,opt,name=filter,proto3" json:"filter,omitempty"`
	TraceFields       *TraceFieldSelection       `protobuf:"bytes,11,opt,name=traceFields,proto3" json:"traceFields,omitempty"`
	TransactionFields *TransactionFieldSelection `protobuf:"bytes,12,opt,name=transactionFields,proto3" json:"transactionFields,omitempty"`
	BlockFields       *BlockFieldSelection       `protobuf:"bytes,13,opt,name=blockFields,proto3" json:"blockFields,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *QueryTracesRequest) Reset() {
	*x = QueryTracesRequest{}
	mi := &file_query_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTracesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTracesRequest) ProtoMessage() {}

func (x *QueryTracesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTracesRequest.ProtoReflect.Descriptor instead.
func (*QueryTracesRequest) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{13}
}

func (x *QueryTracesRequest) GetFromBlock() string {
	if x != nil && x.FromBlock != nil {
		return *x.FromBlock
	}
	return ""
}

func (x *QueryTracesRequest) GetToBlock() string {
	if x != nil && x.ToBlock != nil {
		return *x.ToBlock
	}
	return ""
}

func (x *QueryTracesRequest) GetOrder() SortOrder {
	if x != nil && x.Order != nil {
		return *x.Order
	}
	return SortOrder_ASC
}

func (x *QueryTracesRequest) GetLimit() uint32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *QueryTracesRequest) GetCursor() *CursorBlock {
	if x != nil {
		return x.Cursor
	}
	return nil
}

func (x *QueryTracesRequest) GetChainId() uint64 {
	if x != nil && x.ChainId != nil {
		return *x.ChainId
	}
	return 0
}

func (x *QueryTracesRequest) GetFilter() *TraceFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *QueryTracesRequest) GetTraceFields() *TraceFieldSelection {
	if x != nil {
		return x.TraceFields
	}
	return nil
}

func (x *QueryTracesRequest) GetTransactionFields() *TransactionFieldSelection {
	if x != nil {
		return x.TransactionFields
	}
	return nil
}

func (x *QueryTracesRequest) GetBlockFields() *BlockFieldSelection {
	if x != nil {
		return x.BlockFields
	}
	return nil
}

type QueryTransfersRequest struct {
	state             protoimpl.MessageState     `protogen:"open.v1"`
	FromBlock         *string                    `protobuf:"bytes,1,opt,name=fromBlock,proto3,oneof" json:"fromBlock,omitempty"`
	ToBlock           *string                    `protobuf:"bytes,2,opt,name=toBlock,proto3,oneof" json:"toBlock,omitempty"`
	Order             *SortOrder                 `protobuf:"varint,3,opt,name=order,proto3,enum=bds.evm.SortOrder,oneof" json:"order,omitempty"`
	Limit             *uint32                    `protobuf:"varint,4,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Cursor            *CursorBlock               `protobuf:"bytes,5,opt,name=cursor,proto3,oneof" json:"cursor,omitempty"`
	ChainId           *uint64                    `protobuf:"varint,6,opt,name=chainId,proto3,oneof" json:"chainId,omitempty"`
	Filter            *TransferFilter            `protobuf:"bytes,10,opt,name=filter,proto3" json:"filter,omitempty"`
	TransferFields    *TransferFieldSelection    `protobuf:"bytes,11,opt,name=transferFields,proto3" json:"transferFields,omitempty"`
	TransactionFields *TransactionFieldSelection `protobuf:"bytes,12,opt,name=transactionFields,proto3" json:"transactionFields,omitempty"`
	BlockFields       *BlockFieldSelection       `protobuf:"bytes,13,opt,name=blockFields,proto3" json:"blockFields,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *QueryTransfersRequest) Reset() {
	*x = QueryTransfersRequest{}
	mi := &file_query_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTransfersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTransfersRequest) ProtoMessage() {}

func (x *QueryTransfersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTransfersRequest.ProtoReflect.Descriptor instead.
func (*QueryTransfersRequest) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{14}
}

func (x *QueryTransfersRequest) GetFromBlock() string {
	if x != nil && x.FromBlock != nil {
		return *x.FromBlock
	}
	return ""
}

func (x *QueryTransfersRequest) GetToBlock() string {
	if x != nil && x.ToBlock != nil {
		return *x.ToBlock
	}
	return ""
}

func (x *QueryTransfersRequest) GetOrder() SortOrder {
	if x != nil && x.Order != nil {
		return *x.Order
	}
	return SortOrder_ASC
}

func (x *QueryTransfersRequest) GetLimit() uint32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *QueryTransfersRequest) GetCursor() *CursorBlock {
	if x != nil {
		return x.Cursor
	}
	return nil
}

func (x *QueryTransfersRequest) GetChainId() uint64 {
	if x != nil && x.ChainId != nil {
		return *x.ChainId
	}
	return 0
}

func (x *QueryTransfersRequest) GetFilter() *TransferFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *QueryTransfersRequest) GetTransferFields() *TransferFieldSelection {
	if x != nil {
		return x.TransferFields
	}
	return nil
}

func (x *QueryTransfersRequest) GetTransactionFields() *TransactionFieldSelection {
	if x != nil {
		return x.TransactionFields
	}
	return nil
}

func (x *QueryTransfersRequest) GetBlockFields() *BlockFieldSelection {
	if x != nil {
		return x.BlockFields
	}
	return nil
}

type QueryBlocksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blocks        []*BlockHeader         `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	FromBlock     *CursorBlock           `protobuf:"bytes,2,opt,name=fromBlock,proto3" json:"fromBlock,omitempty"`
	ToBlock       *CursorBlock           `protobuf:"bytes,3,opt,name=toBlock,proto3" json:"toBlock,omitempty"`
	CursorBlock   *CursorBlock           `protobuf:"bytes,4,opt,name=cursorBlock,proto3,oneof" json:"cursorBlock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryBlocksResponse) Reset() {
	*x = QueryBlocksResponse{}
	mi := &file_query_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryBlocksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryBlocksResponse) ProtoMessage() {}

func (x *QueryBlocksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryBlocksResponse.ProtoReflect.Descriptor instead.
func (*QueryBlocksResponse) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{15}
}

func (x *QueryBlocksResponse) GetBlocks() []*BlockHeader {
	if x != nil {
		return x.Blocks
	}
	return nil
}

func (x *QueryBlocksResponse) GetFromBlock() *CursorBlock {
	if x != nil {
		return x.FromBlock
	}
	return nil
}

func (x *QueryBlocksResponse) GetToBlock() *CursorBlock {
	if x != nil {
		return x.ToBlock
	}
	return nil
}

func (x *QueryBlocksResponse) GetCursorBlock() *CursorBlock {
	if x != nil {
		return x.CursorBlock
	}
	return nil
}

type QueryTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Blocks        []*BlockHeader         `protobuf:"bytes,2,rep,name=blocks,proto3" json:"blocks,omitempty"`
	FromBlock     *CursorBlock           `protobuf:"bytes,3,opt,name=fromBlock,proto3" json:"fromBlock,omitempty"`
	ToBlock       *CursorBlock           `protobuf:"bytes,4,opt,name=toBlock,proto3" json:"toBlock,omitempty"`
	CursorBlock   *CursorBlock           `protobuf:"bytes,5,opt,name=cursorBlock,proto3,oneof" json:"cursorBlock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTransactionsResponse) Reset() {
	*x = QueryTransactionsResponse{}
	mi := &file_query_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTransactionsResponse) ProtoMessage() {}

func (x *QueryTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTransactionsResponse.ProtoReflect.Descriptor instead.
func (*QueryTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{16}
}

func (x *QueryTransactionsResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *QueryTransactionsResponse) GetBlocks() []*BlockHeader {
	if x != nil {
		return x.Blocks
	}
	return nil
}

func (x *QueryTransactionsResponse) GetFromBlock() *CursorBlock {
	if x != nil {
		return x.FromBlock
	}
	return nil
}

func (x *QueryTransactionsResponse) GetToBlock() *CursorBlock {
	if x != nil {
		return x.ToBlock
	}
	return nil
}

func (x *QueryTransactionsResponse) GetCursorBlock() *CursorBlock {
	if x != nil {
		return x.CursorBlock
	}
	return nil
}

type QueryLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*Log                 `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	Transactions  []*Transaction         `protobuf:"bytes,2,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Blocks        []*BlockHeader         `protobuf:"bytes,3,rep,name=blocks,proto3" json:"blocks,omitempty"`
	FromBlock     *CursorBlock           `protobuf:"bytes,4,opt,name=fromBlock,proto3" json:"fromBlock,omitempty"`
	ToBlock       *CursorBlock           `protobuf:"bytes,5,opt,name=toBlock,proto3" json:"toBlock,omitempty"`
	CursorBlock   *CursorBlock           `protobuf:"bytes,6,opt,name=cursorBlock,proto3,oneof" json:"cursorBlock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryLogsResponse) Reset() {
	*x = QueryLogsResponse{}
	mi := &file_query_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLogsResponse) ProtoMessage() {}

func (x *QueryLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLogsResponse.ProtoReflect.Descriptor instead.
func (*QueryLogsResponse) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{17}
}

func (x *QueryLogsResponse) GetLogs() []*Log {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *QueryLogsResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *QueryLogsResponse) GetBlocks() []*BlockHeader {
	if x != nil {
		return x.Blocks
	}
	return nil
}

func (x *QueryLogsResponse) GetFromBlock() *CursorBlock {
	if x != nil {
		return x.FromBlock
	}
	return nil
}

func (x *QueryLogsResponse) GetToBlock() *CursorBlock {
	if x != nil {
		return x.ToBlock
	}
	return nil
}

func (x *QueryLogsResponse) GetCursorBlock() *CursorBlock {
	if x != nil {
		return x.CursorBlock
	}
	return nil
}

type QueryTracesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Traces        []*Trace               `protobuf:"bytes,1,rep,name=traces,proto3" json:"traces,omitempty"`
	Transactions  []*Transaction         `protobuf:"bytes,2,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Blocks        []*BlockHeader         `protobuf:"bytes,3,rep,name=blocks,proto3" json:"blocks,omitempty"`
	FromBlock     *CursorBlock           `protobuf:"bytes,4,opt,name=fromBlock,proto3" json:"fromBlock,omitempty"`
	ToBlock       *CursorBlock           `protobuf:"bytes,5,opt,name=toBlock,proto3" json:"toBlock,omitempty"`
	CursorBlock   *CursorBlock           `protobuf:"bytes,6,opt,name=cursorBlock,proto3,oneof" json:"cursorBlock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTracesResponse) Reset() {
	*x = QueryTracesResponse{}
	mi := &file_query_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTracesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTracesResponse) ProtoMessage() {}

func (x *QueryTracesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTracesResponse.ProtoReflect.Descriptor instead.
func (*QueryTracesResponse) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{18}
}

func (x *QueryTracesResponse) GetTraces() []*Trace {
	if x != nil {
		return x.Traces
	}
	return nil
}

func (x *QueryTracesResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *QueryTracesResponse) GetBlocks() []*BlockHeader {
	if x != nil {
		return x.Blocks
	}
	return nil
}

func (x *QueryTracesResponse) GetFromBlock() *CursorBlock {
	if x != nil {
		return x.FromBlock
	}
	return nil
}

func (x *QueryTracesResponse) GetToBlock() *CursorBlock {
	if x != nil {
		return x.ToBlock
	}
	return nil
}

func (x *QueryTracesResponse) GetCursorBlock() *CursorBlock {
	if x != nil {
		return x.CursorBlock
	}
	return nil
}

type QueryTransfersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transfers     []*NativeTransfer      `protobuf:"bytes,1,rep,name=transfers,proto3" json:"transfers,omitempty"`
	Transactions  []*Transaction         `protobuf:"bytes,2,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Blocks        []*BlockHeader         `protobuf:"bytes,3,rep,name=blocks,proto3" json:"blocks,omitempty"`
	FromBlock     *CursorBlock           `protobuf:"bytes,4,opt,name=fromBlock,proto3" json:"fromBlock,omitempty"`
	ToBlock       *CursorBlock           `protobuf:"bytes,5,opt,name=toBlock,proto3" json:"toBlock,omitempty"`
	CursorBlock   *CursorBlock           `protobuf:"bytes,6,opt,name=cursorBlock,proto3,oneof" json:"cursorBlock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTransfersResponse) Reset() {
	*x = QueryTransfersResponse{}
	mi := &file_query_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTransfersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTransfersResponse) ProtoMessage() {}

func (x *QueryTransfersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTransfersResponse.ProtoReflect.Descriptor instead.
func (*QueryTransfersResponse) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{19}
}

func (x *QueryTransfersResponse) GetTransfers() []*NativeTransfer {
	if x != nil {
		return x.Transfers
	}
	return nil
}

func (x *QueryTransfersResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *QueryTransfersResponse) GetBlocks() []*BlockHeader {
	if x != nil {
		return x.Blocks
	}
	return nil
}

func (x *QueryTransfersResponse) GetFromBlock() *CursorBlock {
	if x != nil {
		return x.FromBlock
	}
	return nil
}

func (x *QueryTransfersResponse) GetToBlock() *CursorBlock {
	if x != nil {
		return x.ToBlock
	}
	return nil
}

func (x *QueryTransfersResponse) GetCursorBlock() *CursorBlock {
	if x != nil {
		return x.CursorBlock
	}
	return nil
}

var File_query_proto protoreflect.FileDescriptor

const file_query_proto_rawDesc = "" +
	"\n" +
	"\vquery.proto\x12\abds.evm\x1a\fmodels.proto\x1a\trpc.proto\"Y\n" +
	"\vCursorBlock\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x04R\x06number\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\fR\x04hash\x12\x1e\n" +
	"\n" +
	"parentHash\x18\x03 \x01(\fR\n" +
	"parentHash\"\x9d\x06\n" +
	"\x13BlockFieldSelection\x12\x16\n" +
	"\x06number\x18\x01 \x01(\bR\x06number\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\bR\ttimestamp\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\bR\x04hash\x12\x1e\n" +
	"\n" +
	"parentHash\x18\x04 \x01(\bR\n" +
	"parentHash\x12\x1c\n" +
	"\tstateRoot\x18\x05 \x01(\bR\tstateRoot\x12*\n" +
	"\x10transactionsRoot\x18\x06 \x01(\bR\x10transactionsRoot\x12\"\n" +
	"\freceiptsRoot\x18\a \x01(\bR\freceiptsRoot\x12\x1c\n" +
	"\tlogsBloom\x18\b \x01(\bR\tlogsBloom\x12\x1a\n" +
	"\bgasLimit\x18\t \x01(\bR\bgasLimit\x12\x18\n" +
	"\agasUsed\x18\n" +
	" \x01(\bR\agasUsed\x12\x14\n" +
	"\x05miner\x18\v \x01(\bR\x05miner\x12\x1c\n" +
	"\textraData\x18\f \x01(\bR\textraData\x12\x12\n" +
	"\x04size\x18\r \x01(\bR\x04size\x12\x1e\n" +
	"\n" +
	"sha3Uncles\x18\x0e \x01(\bR\n" +
	"sha3Uncles\x12\x14\n" +
	"\x05nonce\x18\x0f \x01(\bR\x05nonce\x12$\n" +
	"\rbaseFeePerGas\x18\x10 \x01(\bR\rbaseFeePerGas\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x11 \x01(\bR\n" +
	"difficulty\x12(\n" +
	"\x0ftotalDifficulty\x18\x12 \x01(\bR\x0ftotalDifficulty\x12\x18\n" +
	"\amixHash\x18\x13 \x01(\bR\amixHash\x12 \n" +
	"\vblobGasUsed\x18\x14 \x01(\bR\vblobGasUsed\x12$\n" +
	"\rexcessBlobGas\x18\x15 \x01(\bR\rexcessBlobGas\x12(\n" +
	"\x0fwithdrawalsRoot\x18\x16 \x01(\bR\x0fwithdrawalsRoot\x124\n" +
	"\x15parentBeaconBlockRoot\x18\x17 \x01(\bR\x15parentBeaconBlockRoot\x12*\n" +
	"\x10transactionCount\x18\x18 \x01(\bR\x10transactionCount\"\xf1\x05\n" +
	"\x19TransactionFieldSelection\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\bR\x04hash\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\bR\x05nonce\x12\x12\n" +
	"\x04from\x18\x03 \x01(\bR\x04from\x12\x0e\n" +
	"\x02to\x18\x04 \x01(\bR\x02to\x12\x14\n" +
	"\x05value\x18\x05 \x01(\bR\x05value\x12\x14\n" +
	"\x05input\x18\x06 \x01(\bR\x05input\x12\x12\n" +
	"\x04type\x18\a \x01(\bR\x04type\x12\x1a\n" +
	"\bgasLimit\x18\b \x01(\bR\bgasLimit\x12\x1a\n" +
	"\bgasPrice\x18\t \x01(\bR\bgasPrice\x12\"\n" +
	"\fmaxFeePerGas\x18\n" +
	" \x01(\bR\fmaxFeePerGas\x122\n" +
	"\x14maxPriorityFeePerGas\x18\v \x01(\bR\x14maxPriorityFeePerGas\x12\x18\n" +
	"\agasUsed\x18\f \x01(\bR\agasUsed\x12,\n" +
	"\x11effectiveGasPrice\x18\r \x01(\bR\x11effectiveGasPrice\x12 \n" +
	"\vblockNumber\x18\x0e \x01(\bR\vblockNumber\x12\x1c\n" +
	"\tblockHash\x18\x0f \x01(\bR\tblockHash\x12*\n" +
	"\x10transactionIndex\x18\x10 \x01(\bR\x10transactionIndex\x12&\n" +
	"\x0eblockTimestamp\x18\x11 \x01(\bR\x0eblockTimestamp\x12\x18\n" +
	"\achainId\x18\x12 \x01(\bR\achainId\x12\x1e\n" +
	"\n" +
	"accessList\x18\x13 \x01(\bR\n" +
	"accessList\x12*\n" +
	"\x10maxFeePerBlobGas\x18\x14 \x01(\bR\x10maxFeePerBlobGas\x120\n" +
	"\x13blobVersionedHashes\x18\x15 \x01(\bR\x13blobVersionedHashes\x12\f\n" +
	"\x01r\x18\x16 \x01(\bR\x01r\x12\f\n" +
	"\x01s\x18\x17 \x01(\bR\x01s\x12\f\n" +
	"\x01v\x18\x18 \x01(\bR\x01v\x12\x18\n" +
	"\ayParity\x18\x19 \x01(\bR\ayParity\"\xb3\x02\n" +
	"\x11LogFieldSelection\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\bR\aaddress\x12\x16\n" +
	"\x06topics\x18\x02 \x01(\bR\x06topics\x12\x12\n" +
	"\x04data\x18\x03 \x01(\bR\x04data\x12 \n" +
	"\vblockNumber\x18\x04 \x01(\bR\vblockNumber\x12\x1c\n" +
	"\tblockHash\x18\x05 \x01(\bR\tblockHash\x12(\n" +
	"\x0ftransactionHash\x18\x06 \x01(\bR\x0ftransactionHash\x12*\n" +
	"\x10transactionIndex\x18\a \x01(\bR\x10transactionIndex\x12\x1a\n" +
	"\blogIndex\x18\b \x01(\bR\blogIndex\x12&\n" +
	"\x0eblockTimestamp\x18\t \x01(\bR\x0eblockTimestamp\"\xf9\x03\n" +
	"\x13TraceFieldSelection\x12\x1c\n" +
	"\ttraceType\x18\x01 \x01(\bR\ttraceType\x12\x1a\n" +
	"\bcallType\x18\x02 \x01(\bR\bcallType\x12\x12\n" +
	"\x04from\x18\x03 \x01(\bR\x04from\x12\x0e\n" +
	"\x02to\x18\x04 \x01(\bR\x02to\x12\x14\n" +
	"\x05value\x18\x05 \x01(\bR\x05value\x12\x14\n" +
	"\x05input\x18\x06 \x01(\bR\x05input\x12\x16\n" +
	"\x06output\x18\a \x01(\bR\x06output\x12\x10\n" +
	"\x03gas\x18\b \x01(\bR\x03gas\x12\x18\n" +
	"\agasUsed\x18\t \x01(\bR\agasUsed\x12\x14\n" +
	"\x05error\x18\n" +
	" \x01(\bR\x05error\x12\x1c\n" +
	"\tsubtraces\x18\v \x01(\bR\tsubtraces\x12\"\n" +
	"\ftraceAddress\x18\f \x01(\bR\ftraceAddress\x12(\n" +
	"\x0ftransactionHash\x18\r \x01(\bR\x0ftransactionHash\x12*\n" +
	"\x10transactionIndex\x18\x0e \x01(\bR\x10transactionIndex\x12 \n" +
	"\vblockNumber\x18\x0f \x01(\bR\vblockNumber\x12\x1c\n" +
	"\tblockHash\x18\x10 \x01(\bR\tblockHash\x12&\n" +
	"\x0eblockTimestamp\x18\x11 \x01(\bR\x0eblockTimestamp\"\xb4\x02\n" +
	"\x16TransferFieldSelection\x12\x12\n" +
	"\x04from\x18\x01 \x01(\bR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\bR\x02to\x12\x14\n" +
	"\x05value\x18\x03 \x01(\bR\x05value\x12(\n" +
	"\x0ftransactionHash\x18\x04 \x01(\bR\x0ftransactionHash\x12*\n" +
	"\x10transactionIndex\x18\x05 \x01(\bR\x10transactionIndex\x12 \n" +
	"\vblockNumber\x18\x06 \x01(\bR\vblockNumber\x12\x1c\n" +
	"\tblockHash\x18\a \x01(\bR\tblockHash\x12\"\n" +
	"\ftraceAddress\x18\b \x01(\bR\ftraceAddress\x12&\n" +
	"\x0eblockTimestamp\x18\t \x01(\bR\x0eblockTimestamp\"S\n" +
	"\x11TransactionFilter\x12\x12\n" +
	"\x04from\x18\x01 \x03(\fR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x03(\fR\x02to\x12\x1a\n" +
	"\bselector\x18\x03 \x03(\fR\bselector\"S\n" +
	"\tLogFilter\x12\x18\n" +
	"\aaddress\x18\x01 \x03(\fR\aaddress\x12,\n" +
	"\x06topics\x18\x02 \x03(\v2\x14.bds.evm.TopicFilterR\x06topics\"\x81\x01\n" +
	"\vTraceFilter\x12\x12\n" +
	"\x04from\x18\x01 \x03(\fR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x03(\fR\x02to\x12\x1a\n" +
	"\bselector\x18\x03 \x03(\fR\bselector\x12#\n" +
	"\n" +
	"isTopLevel\x18\x04 \x01(\bH\x00R\n" +
	"isTopLevel\x88\x01\x01B\r\n" +
	"\v_isTopLevel\"h\n" +
	"\x0eTransferFilter\x12\x12\n" +
	"\x04from\x18\x01 \x03(\fR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x03(\fR\x02to\x12#\n" +
	"\n" +
	"isTopLevel\x18\x03 \x01(\bH\x00R\n" +
	"isTopLevel\x88\x01\x01B\r\n" +
	"\v_isTopLevel\"\xf7\x02\n" +
	"\x12QueryBlocksRequest\x12!\n" +
	"\tfromBlock\x18\x01 \x01(\tH\x00R\tfromBlock\x88\x01\x01\x12\x1d\n" +
	"\atoBlock\x18\x02 \x01(\tH\x01R\atoBlock\x88\x01\x01\x12-\n" +
	"\x05order\x18\x03 \x01(\x0e2\x12.bds.evm.SortOrderH\x02R\x05order\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x04 \x01(\rH\x03R\x05limit\x88\x01\x01\x121\n" +
	"\x06cursor\x18\x05 \x01(\v2\x14.bds.evm.CursorBlockH\x04R\x06cursor\x88\x01\x01\x12\x1d\n" +
	"\achainId\x18\x06 \x01(\x04H\x05R\achainId\x88\x01\x01\x12>\n" +
	"\vblockFields\x18\n" +
	" \x01(\v2\x1c.bds.evm.BlockFieldSelectionR\vblockFieldsB\f\n" +
	"\n" +
	"_fromBlockB\n" +
	"\n" +
	"\b_toBlockB\b\n" +
	"\x06_orderB\b\n" +
	"\x06_limitB\t\n" +
	"\a_cursorB\n" +
	"\n" +
	"\b_chainId\"\x83\x04\n" +
	"\x18QueryTransactionsRequest\x12!\n" +
	"\tfromBlock\x18\x01 \x01(\tH\x00R\tfromBlock\x88\x01\x01\x12\x1d\n" +
	"\atoBlock\x18\x02 \x01(\tH\x01R\atoBlock\x88\x01\x01\x12-\n" +
	"\x05order\x18\x03 \x01(\x0e2\x12.bds.evm.SortOrderH\x02R\x05order\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x04 \x01(\rH\x03R\x05limit\x88\x01\x01\x121\n" +
	"\x06cursor\x18\x05 \x01(\v2\x14.bds.evm.CursorBlockH\x04R\x06cursor\x88\x01\x01\x12\x1d\n" +
	"\achainId\x18\x06 \x01(\x04H\x05R\achainId\x88\x01\x01\x122\n" +
	"\x06filter\x18\n" +
	" \x01(\v2\x1a.bds.evm.TransactionFilterR\x06filter\x12P\n" +
	"\x11transactionFields\x18\v \x01(\v2\".bds.evm.TransactionFieldSelectionR\x11transactionFields\x12>\n" +
	"\vblockFields\x18\f \x01(\v2\x1c.bds.evm.BlockFieldSelectionR\vblockFieldsB\f\n" +
	"\n" +
	"_fromBlockB\n" +
	"\n" +
	"\b_toBlockB\b\n" +
	"\x06_orderB\b\n" +
	"\x06_limitB\t\n" +
	"\a_cursorB\n" +
	"\n" +
	"\b_chainId\"\xad\x04\n" +
	"\x10QueryLogsRequest\x12!\n" +
	"\tfromBlock\x18\x01 \x01(\tH\x00R\tfromBlock\x88\x01\x01\x12\x1d\n" +
	"\atoBlock\x18\x02 \x01(\tH\x01R\atoBlock\x88\x01\x01\x12-\n" +
	"\x05order\x18\x03 \x01(\x0e2\x12.bds.evm.SortOrderH\x02R\x05order\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x04 \x01(\rH\x03R\x05limit\x88\x01\x01\x121\n" +
	"\x06cursor\x18\x05 \x01(\v2\x14.bds.evm.CursorBlockH\x04R\x06cursor\x88\x01\x01\x12\x1d\n" +
	"\achainId\x18\x06 \x01(\x04H\x05R\achainId\x88\x01\x01\x12*\n" +
	"\x06filter\x18\n" +
	" \x01(\v2\x12.bds.evm.LogFilterR\x06filter\x128\n" +
	"\tlogFields\x18\v \x01(\v2\x1a.bds.evm.LogFieldSelectionR\tlogFields\x12P\n" +
	"\x11transactionFields\x18\f \x01(\v2\".bds.evm.TransactionFieldSelectionR\x11transactionFields\x12>\n" +
	"\vblockFields\x18\r \x01(\v2\x1c.bds.evm.BlockFieldSelectionR\vblockFieldsB\f\n" +
	"\n" +
	"_fromBlockB\n" +
	"\n" +
	"\b_toBlockB\b\n" +
	"\x06_orderB\b\n" +
	"\x06_limitB\t\n" +
	"\a_cursorB\n" +
	"\n" +
	"\b_chainId\"\xb7\x04\n" +
	"\x12QueryTracesRequest\x12!\n" +
	"\tfromBlock\x18\x01 \x01(\tH\x00R\tfromBlock\x88\x01\x01\x12\x1d\n" +
	"\atoBlock\x18\x02 \x01(\tH\x01R\atoBlock\x88\x01\x01\x12-\n" +
	"\x05order\x18\x03 \x01(\x0e2\x12.bds.evm.SortOrderH\x02R\x05order\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x04 \x01(\rH\x03R\x05limit\x88\x01\x01\x121\n" +
	"\x06cursor\x18\x05 \x01(\v2\x14.bds.evm.CursorBlockH\x04R\x06cursor\x88\x01\x01\x12\x1d\n" +
	"\achainId\x18\x06 \x01(\x04H\x05R\achainId\x88\x01\x01\x12,\n" +
	"\x06filter\x18\n" +
	" \x01(\v2\x14.bds.evm.TraceFilterR\x06filter\x12>\n" +
	"\vtraceFields\x18\v \x01(\v2\x1c.bds.evm.TraceFieldSelectionR\vtraceFields\x12P\n" +
	"\x11transactionFields\x18\f \x01(\v2\".bds.evm.TransactionFieldSelectionR\x11transactionFields\x12>\n" +
	"\vblockFields\x18\r \x01(\v2\x1c.bds.evm.BlockFieldSelectionR\vblockFieldsB\f\n" +
	"\n" +
	"_fromBlockB\n" +
	"\n" +
	"\b_toBlockB\b\n" +
	"\x06_orderB\b\n" +
	"\x06_limitB\t\n" +
	"\a_cursorB\n" +
	"\n" +
	"\b_chainId\"\xc6\x04\n" +
	"\x15QueryTransfersRequest\x12!\n" +
	"\tfromBlock\x18\x01 \x01(\tH\x00R\tfromBlock\x88\x01\x01\x12\x1d\n" +
	"\atoBlock\x18\x02 \x01(\tH\x01R\atoBlock\x88\x01\x01\x12-\n" +
	"\x05order\x18\x03 \x01(\x0e2\x12.bds.evm.SortOrderH\x02R\x05order\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x04 \x01(\rH\x03R\x05limit\x88\x01\x01\x121\n" +
	"\x06cursor\x18\x05 \x01(\v2\x14.bds.evm.CursorBlockH\x04R\x06cursor\x88\x01\x01\x12\x1d\n" +
	"\achainId\x18\x06 \x01(\x04H\x05R\achainId\x88\x01\x01\x12/\n" +
	"\x06filter\x18\n" +
	" \x01(\v2\x17.bds.evm.TransferFilterR\x06filter\x12G\n" +
	"\x0etransferFields\x18\v \x01(\v2\x1f.bds.evm.TransferFieldSelectionR\x0etransferFields\x12P\n" +
	"\x11transactionFields\x18\f \x01(\v2\".bds.evm.TransactionFieldSelectionR\x11transactionFields\x12>\n" +
	"\vblockFields\x18\r \x01(\v2\x1c.bds.evm.BlockFieldSelectionR\vblockFieldsB\f\n" +
	"\n" +
	"_fromBlockB\n" +
	"\n" +
	"\b_toBlockB\b\n" +
	"\x06_orderB\b\n" +
	"\x06_limitB\t\n" +
	"\a_cursorB\n" +
	"\n" +
	"\b_chainId\"\xf4\x01\n" +
	"\x13QueryBlocksResponse\x12,\n" +
	"\x06blocks\x18\x01 \x03(\v2\x14.bds.evm.BlockHeaderR\x06blocks\x122\n" +
	"\tfromBlock\x18\x02 \x01(\v2\x14.bds.evm.CursorBlockR\tfromBlock\x12.\n" +
	"\atoBlock\x18\x03 \x01(\v2\x14.bds.evm.CursorBlockR\atoBlock\x12;\n" +
	"\vcursorBlock\x18\x04 \x01(\v2\x14.bds.evm.CursorBlockH\x00R\vcursorBlock\x88\x01\x01B\x0e\n" +
	"\f_cursorBlock\"\xb4\x02\n" +
	"\x19QueryTransactionsResponse\x128\n" +
	"\ftransactions\x18\x01 \x03(\v2\x14.bds.evm.TransactionR\ftransactions\x12,\n" +
	"\x06blocks\x18\x02 \x03(\v2\x14.bds.evm.BlockHeaderR\x06blocks\x122\n" +
	"\tfromBlock\x18\x03 \x01(\v2\x14.bds.evm.CursorBlockR\tfromBlock\x12.\n" +
	"\atoBlock\x18\x04 \x01(\v2\x14.bds.evm.CursorBlockR\atoBlock\x12;\n" +
	"\vcursorBlock\x18\x05 \x01(\v2\x14.bds.evm.CursorBlockH\x00R\vcursorBlock\x88\x01\x01B\x0e\n" +
	"\f_cursorBlock\"\xce\x02\n" +
	"\x11QueryLogsResponse\x12 \n" +
	"\x04logs\x18\x01 \x03(\v2\f.bds.evm.LogR\x04logs\x128\n" +
	"\ftransactions\x18\x02 \x03(\v2\x14.bds.evm.TransactionR\ftransactions\x12,\n" +
	"\x06blocks\x18\x03 \x03(\v2\x14.bds.evm.BlockHeaderR\x06blocks\x122\n" +
	"\tfromBlock\x18\x04 \x01(\v2\x14.bds.evm.CursorBlockR\tfromBlock\x12.\n" +
	"\atoBlock\x18\x05 \x01(\v2\x14.bds.evm.CursorBlockR\atoBlock\x12;\n" +
	"\vcursorBlock\x18\x06 \x01(\v2\x14.bds.evm.CursorBlockH\x00R\vcursorBlock\x88\x01\x01B\x0e\n" +
	"\f_cursorBlock\"\xd6\x02\n" +
	"\x13QueryTracesResponse\x12&\n" +
	"\x06traces\x18\x01 \x03(\v2\x0e.bds.evm.TraceR\x06traces\x128\n" +
	"\ftransactions\x18\x02 \x03(\v2\x14.bds.evm.TransactionR\ftransactions\x12,\n" +
	"\x06blocks\x18\x03 \x03(\v2\x14.bds.evm.BlockHeaderR\x06blocks\x122\n" +
	"\tfromBlock\x18\x04 \x01(\v2\x14.bds.evm.CursorBlockR\tfromBlock\x12.\n" +
	"\atoBlock\x18\x05 \x01(\v2\x14.bds.evm.CursorBlockR\atoBlock\x12;\n" +
	"\vcursorBlock\x18\x06 \x01(\v2\x14.bds.evm.CursorBlockH\x00R\vcursorBlock\x88\x01\x01B\x0e\n" +
	"\f_cursorBlock\"\xe8\x02\n" +
	"\x16QueryTransfersResponse\x125\n" +
	"\ttransfers\x18\x01 \x03(\v2\x17.bds.evm.NativeTransferR\ttransfers\x128\n" +
	"\ftransactions\x18\x02 \x03(\v2\x14.bds.evm.TransactionR\ftransactions\x12,\n" +
	"\x06blocks\x18\x03 \x03(\v2\x14.bds.evm.BlockHeaderR\x06blocks\x122\n" +
	"\tfromBlock\x18\x04 \x01(\v2\x14.bds.evm.CursorBlockR\tfromBlock\x12.\n" +
	"\atoBlock\x18\x05 \x01(\v2\x14.bds.evm.CursorBlockR\atoBlock\x12;\n" +
	"\vcursorBlock\x18\x06 \x01(\v2\x14.bds.evm.CursorBlockH\x00R\vcursorBlock\x88\x01\x01B\x0e\n" +
	"\f_cursorBlock*\x1e\n" +
	"\tSortOrder\x12\a\n" +
	"\x03ASC\x10\x00\x12\b\n" +
	"\x04DESC\x10\x012\x9f\x03\n" +
	"\fQueryService\x12J\n" +
	"\vQueryBlocks\x12\x1b.bds.evm.QueryBlocksRequest\x1a\x1c.bds.evm.QueryBlocksResponse0\x01\x12\\\n" +
	"\x11QueryTransactions\x12!.bds.evm.QueryTransactionsRequest\x1a\".bds.evm.QueryTransactionsResponse0\x01\x12D\n" +
	"\tQueryLogs\x12\x19.bds.evm.QueryLogsRequest\x1a\x1a.bds.evm.QueryLogsResponse0\x01\x12J\n" +
	"\vQueryTraces\x12\x1b.bds.evm.QueryTracesRequest\x1a\x1c.bds.evm.QueryTracesResponse0\x01\x12S\n" +
	"\x0eQueryTransfers\x12\x1e.bds.evm.QueryTransfersRequest\x1a\x1f.bds.evm.QueryTransfersResponse0\x01B4Z2github.com/blockchain-data-standards/manifesto/evmb\x06proto3"

var (
	file_query_proto_rawDescOnce sync.Once
	file_query_proto_rawDescData []byte
)

func file_query_proto_rawDescGZIP() []byte {
	file_query_proto_rawDescOnce.Do(func() {
		file_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_query_proto_rawDesc), len(file_query_proto_rawDesc)))
	})
	return file_query_proto_rawDescData
}

var file_query_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_query_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_query_proto_goTypes = []any{
	(SortOrder)(0),                    // 0: bds.evm.SortOrder
	(*CursorBlock)(nil),               // 1: bds.evm.CursorBlock
	(*BlockFieldSelection)(nil),       // 2: bds.evm.BlockFieldSelection
	(*TransactionFieldSelection)(nil), // 3: bds.evm.TransactionFieldSelection
	(*LogFieldSelection)(nil),         // 4: bds.evm.LogFieldSelection
	(*TraceFieldSelection)(nil),       // 5: bds.evm.TraceFieldSelection
	(*TransferFieldSelection)(nil),    // 6: bds.evm.TransferFieldSelection
	(*TransactionFilter)(nil),         // 7: bds.evm.TransactionFilter
	(*LogFilter)(nil),                 // 8: bds.evm.LogFilter
	(*TraceFilter)(nil),               // 9: bds.evm.TraceFilter
	(*TransferFilter)(nil),            // 10: bds.evm.TransferFilter
	(*QueryBlocksRequest)(nil),        // 11: bds.evm.QueryBlocksRequest
	(*QueryTransactionsRequest)(nil),  // 12: bds.evm.QueryTransactionsRequest
	(*QueryLogsRequest)(nil),          // 13: bds.evm.QueryLogsRequest
	(*QueryTracesRequest)(nil),        // 14: bds.evm.QueryTracesRequest
	(*QueryTransfersRequest)(nil),     // 15: bds.evm.QueryTransfersRequest
	(*QueryBlocksResponse)(nil),       // 16: bds.evm.QueryBlocksResponse
	(*QueryTransactionsResponse)(nil), // 17: bds.evm.QueryTransactionsResponse
	(*QueryLogsResponse)(nil),         // 18: bds.evm.QueryLogsResponse
	(*QueryTracesResponse)(nil),       // 19: bds.evm.QueryTracesResponse
	(*QueryTransfersResponse)(nil),    // 20: bds.evm.QueryTransfersResponse
	(*TopicFilter)(nil),               // 21: bds.evm.TopicFilter
	(*BlockHeader)(nil),               // 22: bds.evm.BlockHeader
	(*Transaction)(nil),               // 23: bds.evm.Transaction
	(*Log)(nil),                       // 24: bds.evm.Log
	(*Trace)(nil),                     // 25: bds.evm.Trace
	(*NativeTransfer)(nil),            // 26: bds.evm.NativeTransfer
}
var file_query_proto_depIdxs = []int32{
	21, // 0: bds.evm.LogFilter.topics:type_name -> bds.evm.TopicFilter
	0,  // 1: bds.evm.QueryBlocksRequest.order:type_name -> bds.evm.SortOrder
	1,  // 2: bds.evm.QueryBlocksRequest.cursor:type_name -> bds.evm.CursorBlock
	2,  // 3: bds.evm.QueryBlocksRequest.blockFields:type_name -> bds.evm.BlockFieldSelection
	0,  // 4: bds.evm.QueryTransactionsRequest.order:type_name -> bds.evm.SortOrder
	1,  // 5: bds.evm.QueryTransactionsRequest.cursor:type_name -> bds.evm.CursorBlock
	7,  // 6: bds.evm.QueryTransactionsRequest.filter:type_name -> bds.evm.TransactionFilter
	3,  // 7: bds.evm.QueryTransactionsRequest.transactionFields:type_name -> bds.evm.TransactionFieldSelection
	2,  // 8: bds.evm.QueryTransactionsRequest.blockFields:type_name -> bds.evm.BlockFieldSelection
	0,  // 9: bds.evm.QueryLogsRequest.order:type_name -> bds.evm.SortOrder
	1,  // 10: bds.evm.QueryLogsRequest.cursor:type_name -> bds.evm.CursorBlock
	8,  // 11: bds.evm.QueryLogsRequest.filter:type_name -> bds.evm.LogFilter
	4,  // 12: bds.evm.QueryLogsRequest.logFields:type_name -> bds.evm.LogFieldSelection
	3,  // 13: bds.evm.QueryLogsRequest.transactionFields:type_name -> bds.evm.TransactionFieldSelection
	2,  // 14: bds.evm.QueryLogsRequest.blockFields:type_name -> bds.evm.BlockFieldSelection
	0,  // 15: bds.evm.QueryTracesRequest.order:type_name -> bds.evm.SortOrder
	1,  // 16: bds.evm.QueryTracesRequest.cursor:type_name -> bds.evm.CursorBlock
	9,  // 17: bds.evm.QueryTracesRequest.filter:type_name -> bds.evm.TraceFilter
	5,  // 18: bds.evm.QueryTracesRequest.traceFields:type_name -> bds.evm.TraceFieldSelection
	3,  // 19: bds.evm.QueryTracesRequest.transactionFields:type_name -> bds.evm.TransactionFieldSelection
	2,  // 20: bds.evm.QueryTracesRequest.blockFields:type_name -> bds.evm.BlockFieldSelection
	0,  // 21: bds.evm.QueryTransfersRequest.order:type_name -> bds.evm.SortOrder
	1,  // 22: bds.evm.QueryTransfersRequest.cursor:type_name -> bds.evm.CursorBlock
	10, // 23: bds.evm.QueryTransfersRequest.filter:type_name -> bds.evm.TransferFilter
	6,  // 24: bds.evm.QueryTransfersRequest.transferFields:type_name -> bds.evm.TransferFieldSelection
	3,  // 25: bds.evm.QueryTransfersRequest.transactionFields:type_name -> bds.evm.TransactionFieldSelection
	2,  // 26: bds.evm.QueryTransfersRequest.blockFields:type_name -> bds.evm.BlockFieldSelection
	22, // 27: bds.evm.QueryBlocksResponse.blocks:type_name -> bds.evm.BlockHeader
	1,  // 28: bds.evm.QueryBlocksResponse.fromBlock:type_name -> bds.evm.CursorBlock
	1,  // 29: bds.evm.QueryBlocksResponse.toBlock:type_name -> bds.evm.CursorBlock
	1,  // 30: bds.evm.QueryBlocksResponse.cursorBlock:type_name -> bds.evm.CursorBlock
	23, // 31: bds.evm.QueryTransactionsResponse.transactions:type_name -> bds.evm.Transaction
	22, // 32: bds.evm.QueryTransactionsResponse.blocks:type_name -> bds.evm.BlockHeader
	1,  // 33: bds.evm.QueryTransactionsResponse.fromBlock:type_name -> bds.evm.CursorBlock
	1,  // 34: bds.evm.QueryTransactionsResponse.toBlock:type_name -> bds.evm.CursorBlock
	1,  // 35: bds.evm.QueryTransactionsResponse.cursorBlock:type_name -> bds.evm.CursorBlock
	24, // 36: bds.evm.QueryLogsResponse.logs:type_name -> bds.evm.Log
	23, // 37: bds.evm.QueryLogsResponse.transactions:type_name -> bds.evm.Transaction
	22, // 38: bds.evm.QueryLogsResponse.blocks:type_name -> bds.evm.BlockHeader
	1,  // 39: bds.evm.QueryLogsResponse.fromBlock:type_name -> bds.evm.CursorBlock
	1,  // 40: bds.evm.QueryLogsResponse.toBlock:type_name -> bds.evm.CursorBlock
	1,  // 41: bds.evm.QueryLogsResponse.cursorBlock:type_name -> bds.evm.CursorBlock
	25, // 42: bds.evm.QueryTracesResponse.traces:type_name -> bds.evm.Trace
	23, // 43: bds.evm.QueryTracesResponse.transactions:type_name -> bds.evm.Transaction
	22, // 44: bds.evm.QueryTracesResponse.blocks:type_name -> bds.evm.BlockHeader
	1,  // 45: bds.evm.QueryTracesResponse.fromBlock:type_name -> bds.evm.CursorBlock
	1,  // 46: bds.evm.QueryTracesResponse.toBlock:type_name -> bds.evm.CursorBlock
	1,  // 47: bds.evm.QueryTracesResponse.cursorBlock:type_name -> bds.evm.CursorBlock
	26, // 48: bds.evm.QueryTransfersResponse.transfers:type_name -> bds.evm.NativeTransfer
	23, // 49: bds.evm.QueryTransfersResponse.transactions:type_name -> bds.evm.Transaction
	22, // 50: bds.evm.QueryTransfersResponse.blocks:type_name -> bds.evm.BlockHeader
	1,  // 51: bds.evm.QueryTransfersResponse.fromBlock:type_name -> bds.evm.CursorBlock
	1,  // 52: bds.evm.QueryTransfersResponse.toBlock:type_name -> bds.evm.CursorBlock
	1,  // 53: bds.evm.QueryTransfersResponse.cursorBlock:type_name -> bds.evm.CursorBlock
	11, // 54: bds.evm.QueryService.QueryBlocks:input_type -> bds.evm.QueryBlocksRequest
	12, // 55: bds.evm.QueryService.QueryTransactions:input_type -> bds.evm.QueryTransactionsRequest
	13, // 56: bds.evm.QueryService.QueryLogs:input_type -> bds.evm.QueryLogsRequest
	14, // 57: bds.evm.QueryService.QueryTraces:input_type -> bds.evm.QueryTracesRequest
	15, // 58: bds.evm.QueryService.QueryTransfers:input_type -> bds.evm.QueryTransfersRequest
	16, // 59: bds.evm.QueryService.QueryBlocks:output_type -> bds.evm.QueryBlocksResponse
	17, // 60: bds.evm.QueryService.QueryTransactions:output_type -> bds.evm.QueryTransactionsResponse
	18, // 61: bds.evm.QueryService.QueryLogs:output_type -> bds.evm.QueryLogsResponse
	19, // 62: bds.evm.QueryService.QueryTraces:output_type -> bds.evm.QueryTracesResponse
	20, // 63: bds.evm.QueryService.QueryTransfers:output_type -> bds.evm.QueryTransfersResponse
	59, // [59:64] is the sub-list for method output_type
	54, // [54:59] is the sub-list for method input_type
	54, // [54:54] is the sub-list for extension type_name
	54, // [54:54] is the sub-list for extension extendee
	0,  // [0:54] is the sub-list for field type_name
}

func init() { file_query_proto_init() }
func file_query_proto_init() {
	if File_query_proto != nil {
		return
	}
	file_models_proto_init()
	file_rpc_proto_init()
	file_query_proto_msgTypes[8].OneofWrappers = []any{}
	file_query_proto_msgTypes[9].OneofWrappers = []any{}
	file_query_proto_msgTypes[10].OneofWrappers = []any{}
	file_query_proto_msgTypes[11].OneofWrappers = []any{}
	file_query_proto_msgTypes[12].OneofWrappers = []any{}
	file_query_proto_msgTypes[13].OneofWrappers = []any{}
	file_query_proto_msgTypes[14].OneofWrappers = []any{}
	file_query_proto_msgTypes[15].OneofWrappers = []any{}
	file_query_proto_msgTypes[16].OneofWrappers = []any{}
	file_query_proto_msgTypes[17].OneofWrappers = []any{}
	file_query_proto_msgTypes[18].OneofWrappers = []any{}
	file_query_proto_msgTypes[19].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_query_proto_rawDesc), len(file_query_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_query_proto_goTypes,
		DependencyIndexes: file_query_proto_depIdxs,
		EnumInfos:         file_query_proto_enumTypes,
		MessageInfos:      file_query_proto_msgTypes,
	}.Build()
	File_query_proto = out.File
	file_query_proto_goTypes = nil
	file_query_proto_depIdxs = nil
}
