// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: stream.proto

package evm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to subscribe to new blocks.
type StreamBlocksRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional chain ID to use for the request (routing is primarily via transport
	// metadata; this is the same optional override the other EVM services accept).
	ChainId *uint64 `protobuf:"varint,1,opt,name=chainId,proto3,oneof" json:"chainId,omitempty"`
	// Optional genesis hash to narrow down identical networks with the same chain ID.
	ChainGenesisHash []byte `protobuf:"bytes,2,opt,name=chainGenesisHash,proto3,oneof" json:"chainGenesisHash,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StreamBlocksRequest) Reset() {
	*x = StreamBlocksRequest{}
	mi := &file_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamBlocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamBlocksRequest) ProtoMessage() {}

func (x *StreamBlocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamBlocksRequest.ProtoReflect.Descriptor instead.
func (*StreamBlocksRequest) Descriptor() ([]byte, []int) {
	return file_stream_proto_rawDescGZIP(), []int{0}
}

func (x *StreamBlocksRequest) GetChainId() uint64 {
	if x != nil && x.ChainId != nil {
		return *x.ChainId
	}
	return 0
}

func (x *StreamBlocksRequest) GetChainGenesisHash() []byte {
	if x != nil {
		return x.ChainGenesisHash
	}
	return nil
}

// A single new block pushed to the subscriber.
type StreamBlocksResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The new block's header.
	Header        *BlockHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamBlocksResponse) Reset() {
	*x = StreamBlocksResponse{}
	mi := &file_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamBlocksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamBlocksResponse) ProtoMessage() {}

func (x *StreamBlocksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamBlocksResponse.ProtoReflect.Descriptor instead.
func (*StreamBlocksResponse) Descriptor() ([]byte, []int) {
	return file_stream_proto_rawDescGZIP(), []int{1}
}

func (x *StreamBlocksResponse) GetHeader() *BlockHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

var File_stream_proto protoreflect.FileDescriptor

const file_stream_proto_rawDesc = "" +
	"\n" +
	"\fstream.proto\x12\abds.evm\x1a\fmodels.proto\"\x86\x01\n" +
	"\x13StreamBlocksRequest\x12\x1d\n" +
	"\achainId\x18\x01 \x01(\x04H\x00R\achainId\x88\x01\x01\x12/\n" +
	"\x10chainGenesisHash\x18\x02 \x01(\fH\x01R\x10chainGenesisHash\x88\x01\x01B\n" +
	"\n" +
	"\b_chainIdB\x13\n" +
	"\x11_chainGenesisHash\"D\n" +
	"\x14StreamBlocksResponse\x12,\n" +
	"\x06header\x18\x01 \x01(\v2\x14.bds.evm.BlockHeaderR\x06header2^\n" +
	"\rStreamService\x12M\n" +
	"\fStreamBlocks\x12\x1c.bds.evm.StreamBlocksRequest\x1a\x1d.bds.evm.StreamBlocksResponse0\x01B4Z2github.com/blockchain-data-standards/manifesto/evmb\x06proto3"

var (
	file_stream_proto_rawDescOnce sync.Once
	file_stream_proto_rawDescData []byte
)

func file_stream_proto_rawDescGZIP() []byte {
	file_stream_proto_rawDescOnce.Do(func() {
		file_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stream_proto_rawDesc), len(file_stream_proto_rawDesc)))
	})
	return file_stream_proto_rawDescData
}

var file_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_stream_proto_goTypes = []any{
	(*StreamBlocksRequest)(nil),  // 0: bds.evm.StreamBlocksRequest
	(*StreamBlocksResponse)(nil), // 1: bds.evm.StreamBlocksResponse
	(*BlockHeader)(nil),          // 2: bds.evm.BlockHeader
}
var file_stream_proto_depIdxs = []int32{
	2, // 0: bds.evm.StreamBlocksResponse.header:type_name -> bds.evm.BlockHeader
	0, // 1: bds.evm.StreamService.StreamBlocks:input_type -> bds.evm.StreamBlocksRequest
	1, // 2: bds.evm.StreamService.StreamBlocks:output_type -> bds.evm.StreamBlocksResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_stream_proto_init() }
func file_stream_proto_init() {
	if File_stream_proto != nil {
		return
	}
	file_models_proto_init()
	file_stream_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stream_proto_rawDesc), len(file_stream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stream_proto_goTypes,
		DependencyIndexes: file_stream_proto_depIdxs,
		MessageInfos:      file_stream_proto_msgTypes,
	}.Build()
	File_stream_proto = out.File
	file_stream_proto_goTypes = nil
	file_stream_proto_depIdxs = nil
}
