// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.0
// source: svm/models.proto

package svm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A confirmed (finalized-sealed) block at a slot.
type ConfirmedBlock struct {
	state             protoimpl.MessageState  `protogen:"open.v1"`
	Slot              uint64                  `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Blockhash         []byte                  `protobuf:"bytes,2,opt,name=blockhash,proto3" json:"blockhash,omitempty"`
	PreviousBlockhash []byte                  `protobuf:"bytes,3,opt,name=previousBlockhash,proto3" json:"previousBlockhash,omitempty"`
	ParentSlot        uint64                  `protobuf:"varint,4,opt,name=parentSlot,proto3" json:"parentSlot,omitempty"`
	BlockHeight       *uint64                 `protobuf:"varint,5,opt,name=blockHeight,proto3,oneof" json:"blockHeight,omitempty"`
	BlockTime         *int64                  `protobuf:"varint,6,opt,name=blockTime,proto3,oneof" json:"blockTime,omitempty"`
	Transactions      []*ConfirmedTransaction `protobuf:"bytes,7,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Rewards           []*Reward               `protobuf:"bytes,8,rep,name=rewards,proto3" json:"rewards,omitempty"`
	// SIMD-0118: present on epoch-boundary blocks since mainnet epoch 707.
	NumRewardPartitions *uint64 `protobuf:"varint,9,opt,name=numRewardPartitions,proto3,oneof" json:"numRewardPartitions,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ConfirmedBlock) Reset() {
	*x = ConfirmedBlock{}
	mi := &file_svm_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmedBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmedBlock) ProtoMessage() {}

func (x *ConfirmedBlock) ProtoReflect() protoreflect.Message {
	mi := &file_svm_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmedBlock.ProtoReflect.Descriptor instead.
func (*ConfirmedBlock) Descriptor() ([]byte, []int) {
	return file_svm_models_proto_rawDescGZIP(), []int{0}
}

func (x *ConfirmedBlock) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *ConfirmedBlock) GetBlockhash() []byte {
	if x != nil {
		return x.Blockhash
	}
	return nil
}

func (x *ConfirmedBlock) GetPreviousBlockhash() []byte {
	if x != nil {
		return x.PreviousBlockhash
	}
	return nil
}

func (x *ConfirmedBlock) GetParentSlot() uint64 {
	if x != nil {
		return x.ParentSlot
	}
	return 0
}

func (x *ConfirmedBlock) GetBlockHeight() uint64 {
	if x != nil && x.BlockHeight != nil {
		return *x.BlockHeight
	}
	return 0
}

func (x *ConfirmedBlock) GetBlockTime() int64 {
	if x != nil && x.BlockTime != nil {
		return *x.BlockTime
	}
	return 0
}

func (x *ConfirmedBlock) GetTransactions() []*ConfirmedTransaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *ConfirmedBlock) GetRewards() []*Reward {
	if x != nil {
		return x.Rewards
	}
	return nil
}

func (x *ConfirmedBlock) GetNumRewardPartitions() uint64 {
	if x != nil && x.NumRewardPartitions != nil {
		return *x.NumRewardPartitions
	}
	return 0
}

// A transaction plus its status meta, as stored in a block.
type ConfirmedTransaction struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Transaction *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Meta        *TransactionStatusMeta `protobuf:"bytes,2,opt,name=meta,proto3,oneof" json:"meta,omitempty"`
	// "legacy" or "0". Absent when unknown. Serving layers must apply
	// maxSupportedTransactionVersion gating (a v0 transaction returned to a
	// client that did not opt in is a protocol error, Agave code -32015).
	Version       *string `protobuf:"bytes,3,opt,name=version,proto3,oneof" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmedTransaction) Reset() {
	*x = ConfirmedTransaction{}
	mi := &file_svm_models_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmedTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmedTransaction) ProtoMessage() {}

func (x *ConfirmedTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_svm_models_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmedTransaction.ProtoReflect.Descriptor instead.
func (*ConfirmedTransaction) Descriptor() ([]byte, []int) {
	return file_svm_models_proto_rawDescGZIP(), []int{1}
}

func (x *ConfirmedTransaction) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *ConfirmedTransaction) GetMeta() *TransactionStatusMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ConfirmedTransaction) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

type Transaction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// First signature is the transaction id.
	Signatures    [][]byte `protobuf:"bytes,1,rep,name=signatures,proto3" json:"signatures,omitempty"`
	Message       *Message `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_svm_models_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_svm_models_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_svm_models_proto_rawDescGZIP(), []int{2}
}

func (x *Transaction) GetSignatures() [][]byte {
	if x != nil {
		return x.Signatures
	}
	return nil
}

func (x *Transaction) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type Message struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Header          *MessageHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	AccountKeys     [][]byte               `protobuf:"bytes,2,rep,name=accountKeys,proto3" json:"accountKeys,omitempty"`
	RecentBlockhash []byte                 `protobuf:"bytes,3,opt,name=recentBlockhash,proto3" json:"recentBlockhash,omitempty"`
	Instructions    []*CompiledInstruction `protobuf:"bytes,4,rep,name=instructions,proto3" json:"instructions,omitempty"`
	// v0 transactions only; empty for legacy.
	AddressTableLookups []*AddressTableLookup `protobuf:"bytes,5,rep,name=addressTableLookups,proto3" json:"addressTableLookups,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_svm_models_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_svm_models_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_svm_models_proto_rawDescGZIP(), []int{3}
}

func (x *Message) GetHeader() *MessageHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Message) GetAccountKeys() [][]byte {
	if x != nil {
		return x.AccountKeys
	}
	return nil
}

func (x *Message) GetRecentBlockhash() []byte {
	if x != nil {
		return x.RecentBlockhash
	}
	return nil
}

func (x *Message) GetInstructions() []*CompiledInstruction {
	if x != nil {
		return x.Instructions
	}
	return nil
}

func (x *Message) GetAddressTableLookups() []*AddressTableLookup {
	if x != nil {
		return x.AddressTableLookups
	}
	return nil
}

type MessageHeader struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	NumRequiredSignatures       uint32                 `protobuf:"varint,1,opt,name=numRequiredSignatures,proto3" json:"numRequiredSignatures,omitempty"`
	NumReadonlySignedAccounts   uint32                 `protobuf:"varint,2,opt,name=numReadonlySignedAccounts,proto3" json:"numReadonlySignedAccounts,omitempty"`
	NumReadonlyUnsignedAccounts uint32                 `protobuf:"varint,3,opt,name=numReadonlyUnsignedAccounts,proto3" json:"numReadonlyUnsignedAccounts,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *MessageHeader) Reset() {
	*x = MessageHeader{}
	mi := &file_svm_models_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageHeader) ProtoMessage() {}

func (x *MessageHeader) ProtoReflect() protoreflect.Message {
	mi := &file_svm_models_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageHeader.ProtoReflect.Descriptor instead.
func (*MessageHeader) Descriptor() ([]byte, []int) {
	return file_svm_models_proto_rawDescGZIP(), []int{4}
}

func (x *MessageHeader) GetNumRequiredSignatures() uint32 {
	if x != nil {
		return x.NumRequiredSignatures
	}
	return 0
}

func (x *MessageHeader) GetNumReadonlySignedAccounts() uint32 {
	if x != nil {
		return x.NumReadonlySignedAccounts
	}
	return 0
}

func (x *MessageHeader) GetNumReadonlyUnsignedAccounts() uint32 {
	if x != nil {
		return x.NumReadonlyUnsignedAccounts
	}
	return 0
}

type CompiledInstruction struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProgramIdIndex uint32                 `protobuf:"varint,1,opt,name=programIdIndex,proto3" json:"programIdIndex,omitempty"`
	// Indexes into the combined account key list.
	Accounts []byte `protobuf:"bytes,2,opt,name=accounts,proto3" json:"accounts,omitempty"`
	// Raw instruction data (decoded from the base58 wire form).
	Data        []byte  `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	StackHeight *uint32 `protobuf:"varint,4,opt,name=stackHeight,proto3,oneof" json:"stackHeight,omitempty"`
	// Agave's ParsedInstruction for this instruction, serde-serialized JSON —
	// {"program","programId","parsed":{...},"stackHeight"} — byte-for-byte what
	// solana-transaction-status emits, so a JSON-RPC layer splices it verbatim.
	// Present only when the request set includeParsed AND one of Agave's
	// parsable programs matched; absent means render partiallyDecoded. The
	// distinction is presence, not emptiness — an empty value never occurs.
	Parsed        []byte `protobuf:"bytes,5,opt,name=parsed,proto3,oneof" json:"parsed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompiledInstruction) Reset() {
	*x = CompiledInstruction{}
	mi := &file_svm_models_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompiledInstruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompiledInstruction) ProtoMessage() {}

func (x *CompiledInstruction) ProtoReflect() protoreflect.Message {
	mi := &file_svm_models_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompiledInstruction.ProtoReflect.Descriptor instead.
func (*CompiledInstruction) Descriptor() ([]byte, []int) {
	return file_svm_models_proto_rawDescGZIP(), []int{5}
}

func (x *CompiledInstruction) GetProgramIdIndex() uint32 {
	if x != nil {
		return x.ProgramIdIndex
	}
	return 0
}

func (x *CompiledInstruction) GetAccounts() []byte {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *CompiledInstruction) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CompiledInstruction) GetStackHeight() uint32 {
	if x != nil && x.StackHeight != nil {
		return *x.StackHeight
	}
	return 0
}

func (x *CompiledInstruction) GetParsed() []byte {
	if x != nil {
		return x.Parsed
	}
	return nil
}

type AddressTableLookup struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccountKey      []byte                 `protobuf:"bytes,1,opt,name=accountKey,proto3" json:"accountKey,omitempty"`
	WritableIndexes []byte                 `protobuf:"bytes,2,opt,name=writableIndexes,proto3" json:"writableIndexes,omitempty"`
	ReadonlyIndexes []byte                 `protobuf:"bytes,3,opt,name=readonlyIndexes,proto3" json:"readonlyIndexes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AddressTableLookup) Reset() {
	*x = AddressTableLookup{}
	mi := &file_svm_models_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressTableLookup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressTableLookup) ProtoMessage() {}

func (x *AddressTableLookup) ProtoReflect() protoreflect.Message {
	mi := &file_svm_models_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressTableLookup.ProtoReflect.Descriptor instead.
func (*AddressTableLookup) Descriptor() ([]byte, []int) {
	return file_svm_models_proto_rawDescGZIP(), []int{6}
}

func (x *AddressTableLookup) GetAccountKey() []byte {
	if x != nil {
		return x.AccountKey
	}
	return nil
}

func (x *AddressTableLookup) GetWritableIndexes() []byte {
	if x != nil {
		return x.WritableIndexes
	}
	return nil
}

func (x *AddressTableLookup) GetReadonlyIndexes() []byte {
	if x != nil {
		return x.ReadonlyIndexes
	}
	return nil
}

type TransactionStatusMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON-stringified TransactionError; absent = success.
	Err               *string              `protobuf:"bytes,1,opt,name=err,proto3,oneof" json:"err,omitempty"`
	Fee               uint64               `protobuf:"varint,2,opt,name=fee,proto3" json:"fee,omitempty"`
	PreBalances       []uint64             `protobuf:"varint,3,rep,packed,name=preBalances,proto3" json:"preBalances,omitempty"`
	PostBalances      []uint64             `protobuf:"varint,4,rep,packed,name=postBalances,proto3" json:"postBalances,omitempty"`
	InnerInstructions []*InnerInstructions `protobuf:"bytes,5,rep,name=innerInstructions,proto3" json:"innerInstructions,omitempty"`
	// True when the source data had `innerInstructions: null` (pre-recording
	// history) as opposed to an empty list.
	InnerInstructionsNone bool            `protobuf:"varint,6,opt,name=innerInstructionsNone,proto3" json:"innerInstructionsNone,omitempty"`
	LogMessages           []string        `protobuf:"bytes,7,rep,name=logMessages,proto3" json:"logMessages,omitempty"`
	LogMessagesNone       bool            `protobuf:"varint,8,opt,name=logMessagesNone,proto3" json:"logMessagesNone,omitempty"`
	PreTokenBalances      []*TokenBalance `protobuf:"bytes,9,rep,name=preTokenBalances,proto3" json:"preTokenBalances,omitempty"`
	PreTokenBalancesNone  bool            `protobuf:"varint,10,opt,name=preTokenBalancesNone,proto3" json:"preTokenBalancesNone,omitempty"`
	PostTokenBalances     []*TokenBalance `protobuf:"bytes,11,rep,name=postTokenBalances,proto3" json:"postTokenBalances,omitempty"`
	PostTokenBalancesNone bool            `protobuf:"varint,12,opt,name=postTokenBalancesNone,proto3" json:"postTokenBalancesNone,omitempty"`
	Rewards               []*Reward       `protobuf:"bytes,13,rep,name=rewards,proto3" json:"rewards,omitempty"`
	RewardsNone           bool            `protobuf:"varint,14,opt,name=rewardsNone,proto3" json:"rewardsNone,omitempty"`
	// v0 address-table-resolved accounts; empty for legacy transactions.
	LoadedWritableAddresses [][]byte    `protobuf:"bytes,15,rep,name=loadedWritableAddresses,proto3" json:"loadedWritableAddresses,omitempty"`
	LoadedReadonlyAddresses [][]byte    `protobuf:"bytes,16,rep,name=loadedReadonlyAddresses,proto3" json:"loadedReadonlyAddresses,omitempty"`
	ReturnData              *ReturnData `protobuf:"bytes,17,opt,name=returnData,proto3,oneof" json:"returnData,omitempty"`
	ComputeUnitsConsumed    *uint64     `protobuf:"varint,18,opt,name=computeUnitsConsumed,proto3,oneof" json:"computeUnitsConsumed,omitempty"`
	// Agave v3.x-era addition; absent on older history.
	CostUnits     *uint64 `protobuf:"varint,19,opt,name=costUnits,proto3,oneof" json:"costUnits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionStatusMeta) Reset() {
	*x = TransactionStatusMeta{}
	mi := &file_svm_models_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionStatusMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionStatusMeta) ProtoMessage() {}

func (x *TransactionStatusMeta) ProtoReflect() protoreflect.Message {
	mi := &file_svm_models_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionStatusMeta.ProtoReflect.Descriptor instead.
func (*TransactionStatusMeta) Descriptor() ([]byte, []int) {
	return file_svm_models_proto_rawDescGZIP(), []int{7}
}

func (x *TransactionStatusMeta) GetErr() string {
	if x != nil && x.Err != nil {
		return *x.Err
	}
	return ""
}

func (x *TransactionStatusMeta) GetFee() uint64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *TransactionStatusMeta) GetPreBalances() []uint64 {
	if x != nil {
		return x.PreBalances
	}
	return nil
}

func (x *TransactionStatusMeta) GetPostBalances() []uint64 {
	if x != nil {
		return x.PostBalances
	}
	return nil
}

func (x *TransactionStatusMeta) GetInnerInstructions() []*InnerInstructions {
	if x != nil {
		return x.InnerInstructions
	}
	return nil
}

func (x *TransactionStatusMeta) GetInnerInstructionsNone() bool {
	if x != nil {
		return x.InnerInstructionsNone
	}
	return false
}

func (x *TransactionStatusMeta) GetLogMessages() []string {
	if x != nil {
		return x.LogMessages
	}
	return nil
}

func (x *TransactionStatusMeta) GetLogMessagesNone() bool {
	if x != nil {
		return x.LogMessagesNone
	}
	return false
}

func (x *TransactionStatusMeta) GetPreTokenBalances() []*TokenBalance {
	if x != nil {
		return x.PreTokenBalances
	}
	return nil
}

func (x *TransactionStatusMeta) GetPreTokenBalancesNone() bool {
	if x != nil {
		return x.PreTokenBalancesNone
	}
	return false
}

func (x *TransactionStatusMeta) GetPostTokenBalances() []*TokenBalance {
	if x != nil {
		return x.PostTokenBalances
	}
	return nil
}

func (x *TransactionStatusMeta) GetPostTokenBalancesNone() bool {
	if x != nil {
		return x.PostTokenBalancesNone
	}
	return false
}

func (x *TransactionStatusMeta) GetRewards() []*Reward {
	if x != nil {
		return x.Rewards
	}
	return nil
}

func (x *TransactionStatusMeta) GetRewardsNone() bool {
	if x != nil {
		return x.RewardsNone
	}
	return false
}

func (x *TransactionStatusMeta) GetLoadedWritableAddresses() [][]byte {
	if x != nil {
		return x.LoadedWritableAddresses
	}
	return nil
}

func (x *TransactionStatusMeta) GetLoadedReadonlyAddresses() [][]byte {
	if x != nil {
		return x.LoadedReadonlyAddresses
	}
	return nil
}

func (x *TransactionStatusMeta) GetReturnData() *ReturnData {
	if x != nil {
		return x.ReturnData
	}
	return nil
}

func (x *TransactionStatusMeta) GetComputeUnitsConsumed() uint64 {
	if x != nil && x.ComputeUnitsConsumed != nil {
		return *x.ComputeUnitsConsumed
	}
	return 0
}

func (x *TransactionStatusMeta) GetCostUnits() uint64 {
	if x != nil && x.CostUnits != nil {
		return *x.CostUnits
	}
	return 0
}

type InnerInstructions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Index of the top-level instruction these inner instructions belong to.
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Instructions  []*CompiledInstruction `protobuf:"bytes,2,rep,name=instructions,proto3" json:"instructions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InnerInstructions) Reset() {
	*x = InnerInstructions{}
	mi := &file_svm_models_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InnerInstructions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InnerInstructions) ProtoMessage() {}

func (x *InnerInstructions) ProtoReflect() protoreflect.Message {
	mi := &file_svm_models_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InnerInstructions.ProtoReflect.Descriptor instead.
func (*InnerInstructions) Descriptor() ([]byte, []int) {
	return file_svm_models_proto_rawDescGZIP(), []int{8}
}

func (x *InnerInstructions) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *InnerInstructions) GetInstructions() []*CompiledInstruction {
	if x != nil {
		return x.Instructions
	}
	return nil
}

type TokenBalance struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	AccountIndex uint32                 `protobuf:"varint,1,opt,name=accountIndex,proto3" json:"accountIndex,omitempty"`
	// Mint and owner are base58-decoded 32-byte keys.
	Mint          []byte         `protobuf:"bytes,2,opt,name=mint,proto3" json:"mint,omitempty"`
	Owner         []byte         `protobuf:"bytes,3,opt,name=owner,proto3,oneof" json:"owner,omitempty"`
	ProgramId     []byte         `protobuf:"bytes,4,opt,name=programId,proto3,oneof" json:"programId,omitempty"`
	UiTokenAmount *UiTokenAmount `protobuf:"bytes,5,opt,name=uiTokenAmount,proto3" json:"uiTokenAmount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenBalance) Reset() {
	*x = TokenBalance{}
	mi := &file_svm_models_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenBalance) ProtoMessage() {}

func (x *TokenBalance) ProtoReflect() protoreflect.Message {
	mi := &file_svm_models_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenBalance.ProtoReflect.Descriptor instead.
func (*TokenBalance) Descriptor() ([]byte, []int) {
	return file_svm_models_proto_rawDescGZIP(), []int{9}
}

func (x *TokenBalance) GetAccountIndex() uint32 {
	if x != nil {
		return x.AccountIndex
	}
	return 0
}

func (x *TokenBalance) GetMint() []byte {
	if x != nil {
		return x.Mint
	}
	return nil
}

func (x *TokenBalance) GetOwner() []byte {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *TokenBalance) GetProgramId() []byte {
	if x != nil {
		return x.ProgramId
	}
	return nil
}

func (x *TokenBalance) GetUiTokenAmount() *UiTokenAmount {
	if x != nil {
		return x.UiTokenAmount
	}
	return nil
}

type UiTokenAmount struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw token amount as a decimal string (u64-range, kept as string per
	// Solana JSON-RPC; never reformat).
	Amount   string `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Decimals uint32 `protobuf:"varint,2,opt,name=decimals,proto3" json:"decimals,omitempty"`
	// uiAmountString from the source; preferred over the lossy float form.
	UiAmountString *string `protobuf:"bytes,3,opt,name=uiAmountString,proto3,oneof" json:"uiAmountString,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UiTokenAmount) Reset() {
	*x = UiTokenAmount{}
	mi := &file_svm_models_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UiTokenAmount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UiTokenAmount) ProtoMessage() {}

func (x *UiTokenAmount) ProtoReflect() protoreflect.Message {
	mi := &file_svm_models_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UiTokenAmount.ProtoReflect.Descriptor instead.
func (*UiTokenAmount) Descriptor() ([]byte, []int) {
	return file_svm_models_proto_rawDescGZIP(), []int{10}
}

func (x *UiTokenAmount) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *UiTokenAmount) GetDecimals() uint32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *UiTokenAmount) GetUiAmountString() string {
	if x != nil && x.UiAmountString != nil {
		return *x.UiAmountString
	}
	return ""
}

type ReturnData struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ProgramId []byte                 `protobuf:"bytes,1,opt,name=programId,proto3" json:"programId,omitempty"`
	// Raw bytes (decoded from the base64 wire form).
	Data          []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReturnData) Reset() {
	*x = ReturnData{}
	mi := &file_svm_models_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReturnData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnData) ProtoMessage() {}

func (x *ReturnData) ProtoReflect() protoreflect.Message {
	mi := &file_svm_models_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnData.ProtoReflect.Descriptor instead.
func (*ReturnData) Descriptor() ([]byte, []int) {
	return file_svm_models_proto_rawDescGZIP(), []int{11}
}

func (x *ReturnData) GetProgramId() []byte {
	if x != nil {
		return x.ProgramId
	}
	return nil
}

func (x *ReturnData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Reward struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Pubkey []byte                 `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	// Can be negative (e.g. rent debits in old history).
	Lamports    int64   `protobuf:"varint,2,opt,name=lamports,proto3" json:"lamports,omitempty"`
	PostBalance *uint64 `protobuf:"varint,3,opt,name=postBalance,proto3,oneof" json:"postBalance,omitempty"`
	// "Fee" | "Rent" | "Voting" | "Staking" — kept verbatim.
	RewardType    *string `protobuf:"bytes,4,opt,name=rewardType,proto3,oneof" json:"rewardType,omitempty"`
	Commission    *uint32 `protobuf:"varint,5,opt,name=commission,proto3,oneof" json:"commission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reward) Reset() {
	*x = Reward{}
	mi := &file_svm_models_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reward) ProtoMessage() {}

func (x *Reward) ProtoReflect() protoreflect.Message {
	mi := &file_svm_models_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reward.ProtoReflect.Descriptor instead.
func (*Reward) Descriptor() ([]byte, []int) {
	return file_svm_models_proto_rawDescGZIP(), []int{12}
}

func (x *Reward) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

func (x *Reward) GetLamports() int64 {
	if x != nil {
		return x.Lamports
	}
	return 0
}

func (x *Reward) GetPostBalance() uint64 {
	if x != nil && x.PostBalance != nil {
		return *x.PostBalance
	}
	return 0
}

func (x *Reward) GetRewardType() string {
	if x != nil && x.RewardType != nil {
		return *x.RewardType
	}
	return ""
}

func (x *Reward) GetCommission() uint32 {
	if x != nil && x.Commission != nil {
		return *x.Commission
	}
	return 0
}

var File_svm_models_proto protoreflect.FileDescriptor

const file_svm_models_proto_rawDesc = "" +
	"\n" +
	"\x10svm/models.proto\x12\abds.svm\"\xb5\x03\n" +
	"\x0eConfirmedBlock\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x04R\x04slot\x12\x1c\n" +
	"\tblockhash\x18\x02 \x01(\fR\tblockhash\x12,\n" +
	"\x11previousBlockhash\x18\x03 \x01(\fR\x11previousBlockhash\x12\x1e\n" +
	"\n" +
	"parentSlot\x18\x04 \x01(\x04R\n" +
	"parentSlot\x12%\n" +
	"\vblockHeight\x18\x05 \x01(\x04H\x00R\vblockHeight\x88\x01\x01\x12!\n" +
	"\tblockTime\x18\x06 \x01(\x03H\x01R\tblockTime\x88\x01\x01\x12A\n" +
	"\ftransactions\x18\a \x03(\v2\x1d.bds.svm.ConfirmedTransactionR\ftransactions\x12)\n" +
	"\arewards\x18\b \x03(\v2\x0f.bds.svm.RewardR\arewards\x125\n" +
	"\x13numRewardPartitions\x18\t \x01(\x04H\x02R\x13numRewardPartitions\x88\x01\x01B\x0e\n" +
	"\f_blockHeightB\f\n" +
	"\n" +
	"_blockTimeB\x16\n" +
	"\x14_numRewardPartitions\"\xbb\x01\n" +
	"\x14ConfirmedTransaction\x126\n" +
	"\vtransaction\x18\x01 \x01(\v2\x14.bds.svm.TransactionR\vtransaction\x127\n" +
	"\x04meta\x18\x02 \x01(\v2\x1e.bds.svm.TransactionStatusMetaH\x00R\x04meta\x88\x01\x01\x12\x1d\n" +
	"\aversion\x18\x03 \x01(\tH\x01R\aversion\x88\x01\x01B\a\n" +
	"\x05_metaB\n" +
	"\n" +
	"\b_version\"Y\n" +
	"\vTransaction\x12\x1e\n" +
	"\n" +
	"signatures\x18\x01 \x03(\fR\n" +
	"signatures\x12*\n" +
	"\amessage\x18\x02 \x01(\v2\x10.bds.svm.MessageR\amessage\"\x96\x02\n" +
	"\aMessage\x12.\n" +
	"\x06header\x18\x01 \x01(\v2\x16.bds.svm.MessageHeaderR\x06header\x12 \n" +
	"\vaccountKeys\x18\x02 \x03(\fR\vaccountKeys\x12(\n" +
	"\x0frecentBlockhash\x18\x03 \x01(\fR\x0frecentBlockhash\x12@\n" +
	"\finstructions\x18\x04 \x03(\v2\x1c.bds.svm.CompiledInstructionR\finstructions\x12M\n" +
	"\x13addressTableLookups\x18\x05 \x03(\v2\x1b.bds.svm.AddressTableLookupR\x13addressTableLookups\"\xc5\x01\n" +
	"\rMessageHeader\x124\n" +
	"\x15numRequiredSignatures\x18\x01 \x01(\rR\x15numRequiredSignatures\x12<\n" +
	"\x19numReadonlySignedAccounts\x18\x02 \x01(\rR\x19numReadonlySignedAccounts\x12@\n" +
	"\x1bnumReadonlyUnsignedAccounts\x18\x03 \x01(\rR\x1bnumReadonlyUnsignedAccounts\"\xcc\x01\n" +
	"\x13CompiledInstruction\x12&\n" +
	"\x0eprogramIdIndex\x18\x01 \x01(\rR\x0eprogramIdIndex\x12\x1a\n" +
	"\baccounts\x18\x02 \x01(\fR\baccounts\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12%\n" +
	"\vstackHeight\x18\x04 \x01(\rH\x00R\vstackHeight\x88\x01\x01\x12\x1b\n" +
	"\x06parsed\x18\x05 \x01(\fH\x01R\x06parsed\x88\x01\x01B\x0e\n" +
	"\f_stackHeightB\t\n" +
	"\a_parsed\"\x88\x01\n" +
	"\x12AddressTableLookup\x12\x1e\n" +
	"\n" +
	"accountKey\x18\x01 \x01(\fR\n" +
	"accountKey\x12(\n" +
	"\x0fwritableIndexes\x18\x02 \x01(\fR\x0fwritableIndexes\x12(\n" +
	"\x0freadonlyIndexes\x18\x03 \x01(\fR\x0freadonlyIndexes\"\xd9\a\n" +
	"\x15TransactionStatusMeta\x12\x15\n" +
	"\x03err\x18\x01 \x01(\tH\x00R\x03err\x88\x01\x01\x12\x10\n" +
	"\x03fee\x18\x02 \x01(\x04R\x03fee\x12 \n" +
	"\vpreBalances\x18\x03 \x03(\x04R\vpreBalances\x12\"\n" +
	"\fpostBalances\x18\x04 \x03(\x04R\fpostBalances\x12H\n" +
	"\x11innerInstructions\x18\x05 \x03(\v2\x1a.bds.svm.InnerInstructionsR\x11innerInstructions\x124\n" +
	"\x15innerInstructionsNone\x18\x06 \x01(\bR\x15innerInstructionsNone\x12 \n" +
	"\vlogMessages\x18\a \x03(\tR\vlogMessages\x12(\n" +
	"\x0flogMessagesNone\x18\b \x01(\bR\x0flogMessagesNone\x12A\n" +
	"\x10preTokenBalances\x18\t \x03(\v2\x15.bds.svm.TokenBalanceR\x10preTokenBalances\x122\n" +
	"\x14preTokenBalancesNone\x18\n" +
	" \x01(\bR\x14preTokenBalancesNone\x12C\n" +
	"\x11postTokenBalances\x18\v \x03(\v2\x15.bds.svm.TokenBalanceR\x11postTokenBalances\x124\n" +
	"\x15postTokenBalancesNone\x18\f \x01(\bR\x15postTokenBalancesNone\x12)\n" +
	"\arewards\x18\r \x03(\v2\x0f.bds.svm.RewardR\arewards\x12 \n" +
	"\vrewardsNone\x18\x0e \x01(\bR\vrewardsNone\x128\n" +
	"\x17loadedWritableAddresses\x18\x0f \x03(\fR\x17loadedWritableAddresses\x128\n" +
	"\x17loadedReadonlyAddresses\x18\x10 \x03(\fR\x17loadedReadonlyAddresses\x128\n" +
	"\n" +
	"returnData\x18\x11 \x01(\v2\x13.bds.svm.ReturnDataH\x01R\n" +
	"returnData\x88\x01\x01\x127\n" +
	"\x14computeUnitsConsumed\x18\x12 \x01(\x04H\x02R\x14computeUnitsConsumed\x88\x01\x01\x12!\n" +
	"\tcostUnits\x18\x13 \x01(\x04H\x03R\tcostUnits\x88\x01\x01B\x06\n" +
	"\x04_errB\r\n" +
	"\v_returnDataB\x17\n" +
	"\x15_computeUnitsConsumedB\f\n" +
	"\n" +
	"_costUnits\"k\n" +
	"\x11InnerInstructions\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12@\n" +
	"\finstructions\x18\x02 \x03(\v2\x1c.bds.svm.CompiledInstructionR\finstructions\"\xda\x01\n" +
	"\fTokenBalance\x12\"\n" +
	"\faccountIndex\x18\x01 \x01(\rR\faccountIndex\x12\x12\n" +
	"\x04mint\x18\x02 \x01(\fR\x04mint\x12\x19\n" +
	"\x05owner\x18\x03 \x01(\fH\x00R\x05owner\x88\x01\x01\x12!\n" +
	"\tprogramId\x18\x04 \x01(\fH\x01R\tprogramId\x88\x01\x01\x12<\n" +
	"\ruiTokenAmount\x18\x05 \x01(\v2\x16.bds.svm.UiTokenAmountR\ruiTokenAmountB\b\n" +
	"\x06_ownerB\f\n" +
	"\n" +
	"_programId\"\x83\x01\n" +
	"\rUiTokenAmount\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\tR\x06amount\x12\x1a\n" +
	"\bdecimals\x18\x02 \x01(\rR\bdecimals\x12+\n" +
	"\x0euiAmountString\x18\x03 \x01(\tH\x00R\x0euiAmountString\x88\x01\x01B\x11\n" +
	"\x0f_uiAmountString\">\n" +
	"\n" +
	"ReturnData\x12\x1c\n" +
	"\tprogramId\x18\x01 \x01(\fR\tprogramId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\xdb\x01\n" +
	"\x06Reward\x12\x16\n" +
	"\x06pubkey\x18\x01 \x01(\fR\x06pubkey\x12\x1a\n" +
	"\blamports\x18\x02 \x01(\x03R\blamports\x12%\n" +
	"\vpostBalance\x18\x03 \x01(\x04H\x00R\vpostBalance\x88\x01\x01\x12#\n" +
	"\n" +
	"rewardType\x18\x04 \x01(\tH\x01R\n" +
	"rewardType\x88\x01\x01\x12#\n" +
	"\n" +
	"commission\x18\x05 \x01(\rH\x02R\n" +
	"commission\x88\x01\x01B\x0e\n" +
	"\f_postBalanceB\r\n" +
	"\v_rewardTypeB\r\n" +
	"\v_commissionB4Z2github.com/blockchain-data-standards/manifesto/svmb\x06proto3"

var (
	file_svm_models_proto_rawDescOnce sync.Once
	file_svm_models_proto_rawDescData []byte
)

func file_svm_models_proto_rawDescGZIP() []byte {
	file_svm_models_proto_rawDescOnce.Do(func() {
		file_svm_models_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_svm_models_proto_rawDesc), len(file_svm_models_proto_rawDesc)))
	})
	return file_svm_models_proto_rawDescData
}

var file_svm_models_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_svm_models_proto_goTypes = []any{
	(*ConfirmedBlock)(nil),        // 0: bds.svm.ConfirmedBlock
	(*ConfirmedTransaction)(nil),  // 1: bds.svm.ConfirmedTransaction
	(*Transaction)(nil),           // 2: bds.svm.Transaction
	(*Message)(nil),               // 3: bds.svm.Message
	(*MessageHeader)(nil),         // 4: bds.svm.MessageHeader
	(*CompiledInstruction)(nil),   // 5: bds.svm.CompiledInstruction
	(*AddressTableLookup)(nil),    // 6: bds.svm.AddressTableLookup
	(*TransactionStatusMeta)(nil), // 7: bds.svm.TransactionStatusMeta
	(*InnerInstructions)(nil),     // 8: bds.svm.InnerInstructions
	(*TokenBalance)(nil),          // 9: bds.svm.TokenBalance
	(*UiTokenAmount)(nil),         // 10: bds.svm.UiTokenAmount
	(*ReturnData)(nil),            // 11: bds.svm.ReturnData
	(*Reward)(nil),                // 12: bds.svm.Reward
}
var file_svm_models_proto_depIdxs = []int32{
	1,  // 0: bds.svm.ConfirmedBlock.transactions:type_name -> bds.svm.ConfirmedTransaction
	12, // 1: bds.svm.ConfirmedBlock.rewards:type_name -> bds.svm.Reward
	2,  // 2: bds.svm.ConfirmedTransaction.transaction:type_name -> bds.svm.Transaction
	7,  // 3: bds.svm.ConfirmedTransaction.meta:type_name -> bds.svm.TransactionStatusMeta
	3,  // 4: bds.svm.Transaction.message:type_name -> bds.svm.Message
	4,  // 5: bds.svm.Message.header:type_name -> bds.svm.MessageHeader
	5,  // 6: bds.svm.Message.instructions:type_name -> bds.svm.CompiledInstruction
	6,  // 7: bds.svm.Message.addressTableLookups:type_name -> bds.svm.AddressTableLookup
	8,  // 8: bds.svm.TransactionStatusMeta.innerInstructions:type_name -> bds.svm.InnerInstructions
	9,  // 9: bds.svm.TransactionStatusMeta.preTokenBalances:type_name -> bds.svm.TokenBalance
	9,  // 10: bds.svm.TransactionStatusMeta.postTokenBalances:type_name -> bds.svm.TokenBalance
	12, // 11: bds.svm.TransactionStatusMeta.rewards:type_name -> bds.svm.Reward
	11, // 12: bds.svm.TransactionStatusMeta.returnData:type_name -> bds.svm.ReturnData
	5,  // 13: bds.svm.InnerInstructions.instructions:type_name -> bds.svm.CompiledInstruction
	10, // 14: bds.svm.TokenBalance.uiTokenAmount:type_name -> bds.svm.UiTokenAmount
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_svm_models_proto_init() }
func file_svm_models_proto_init() {
	if File_svm_models_proto != nil {
		return
	}
	file_svm_models_proto_msgTypes[0].OneofWrappers = []any{}
	file_svm_models_proto_msgTypes[1].OneofWrappers = []any{}
	file_svm_models_proto_msgTypes[5].OneofWrappers = []any{}
	file_svm_models_proto_msgTypes[7].OneofWrappers = []any{}
	file_svm_models_proto_msgTypes[9].OneofWrappers = []any{}
	file_svm_models_proto_msgTypes[10].OneofWrappers = []any{}
	file_svm_models_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_svm_models_proto_rawDesc), len(file_svm_models_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_svm_models_proto_goTypes,
		DependencyIndexes: file_svm_models_proto_depIdxs,
		MessageInfos:      file_svm_models_proto_msgTypes,
	}.Build()
	File_svm_models_proto = out.File
	file_svm_models_proto_goTypes = nil
	file_svm_models_proto_depIdxs = nil
}
