// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: rpc.proto

package svm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Commitment level for read visibility. FINALIZED is the zero value on
// purpose: it is Agave's default for every history method.
type Commitment int32

const (
	Commitment_COMMITMENT_FINALIZED Commitment = 0
	Commitment_COMMITMENT_CONFIRMED Commitment = 1
)

// Enum value maps for Commitment.
var (
	Commitment_name = map[int32]string{
		0: "COMMITMENT_FINALIZED",
		1: "COMMITMENT_CONFIRMED",
	}
	Commitment_value = map[string]int32{
		"COMMITMENT_FINALIZED": 0,
		"COMMITMENT_CONFIRMED": 1,
	}
)

func (x Commitment) Enum() *Commitment {
	p := new(Commitment)
	*p = x
	return p
}

func (x Commitment) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Commitment) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_proto_enumTypes[0].Descriptor()
}

func (Commitment) Type() protoreflect.EnumType {
	return &file_rpc_proto_enumTypes[0]
}

func (x Commitment) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Commitment.Descriptor instead.
func (Commitment) EnumDescriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{0}
}

// Whether a slot holds a block or was skipped (leader produced no block /
// fork abandoned). Only meaningful for slots at or below the finalized
// watermark — skip status is not knowable earlier.
type SlotStatus int32

const (
	SlotStatus_SLOT_PRESENT SlotStatus = 0
	SlotStatus_SLOT_SKIPPED SlotStatus = 1
)

// Enum value maps for SlotStatus.
var (
	SlotStatus_name = map[int32]string{
		0: "SLOT_PRESENT",
		1: "SLOT_SKIPPED",
	}
	SlotStatus_value = map[string]int32{
		"SLOT_PRESENT": 0,
		"SLOT_SKIPPED": 1,
	}
)

func (x SlotStatus) Enum() *SlotStatus {
	p := new(SlotStatus)
	*p = x
	return p
}

func (x SlotStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SlotStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_proto_enumTypes[1].Descriptor()
}

func (SlotStatus) Type() protoreflect.EnumType {
	return &file_rpc_proto_enumTypes[1]
}

func (x SlotStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SlotStatus.Descriptor instead.
func (SlotStatus) EnumDescriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{1}
}

// Mirror of getBlock's transactionDetails parameter.
type TransactionDetails int32

const (
	TransactionDetails_TRANSACTION_DETAILS_FULL       TransactionDetails = 0
	TransactionDetails_TRANSACTION_DETAILS_ACCOUNTS   TransactionDetails = 1
	TransactionDetails_TRANSACTION_DETAILS_SIGNATURES TransactionDetails = 2
	TransactionDetails_TRANSACTION_DETAILS_NONE       TransactionDetails = 3
)

// Enum value maps for TransactionDetails.
var (
	TransactionDetails_name = map[int32]string{
		0: "TRANSACTION_DETAILS_FULL",
		1: "TRANSACTION_DETAILS_ACCOUNTS",
		2: "TRANSACTION_DETAILS_SIGNATURES",
		3: "TRANSACTION_DETAILS_NONE",
	}
	TransactionDetails_value = map[string]int32{
		"TRANSACTION_DETAILS_FULL":       0,
		"TRANSACTION_DETAILS_ACCOUNTS":   1,
		"TRANSACTION_DETAILS_SIGNATURES": 2,
		"TRANSACTION_DETAILS_NONE":       3,
	}
)

func (x TransactionDetails) Enum() *TransactionDetails {
	p := new(TransactionDetails)
	*p = x
	return p
}

func (x TransactionDetails) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionDetails) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_proto_enumTypes[2].Descriptor()
}

func (TransactionDetails) Type() protoreflect.EnumType {
	return &file_rpc_proto_enumTypes[2]
}

func (x TransactionDetails) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionDetails.Descriptor instead.
func (TransactionDetails) EnumDescriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{2}
}

type GetGenesisHashRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGenesisHashRequest) Reset() {
	*x = GetGenesisHashRequest{}
	mi := &file_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGenesisHashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGenesisHashRequest) ProtoMessage() {}

func (x *GetGenesisHashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGenesisHashRequest.ProtoReflect.Descriptor instead.
func (*GetGenesisHashRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{0}
}

type GetGenesisHashResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GenesisHash   []byte                 `protobuf:"bytes,1,opt,name=genesisHash,proto3" json:"genesisHash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGenesisHashResponse) Reset() {
	*x = GetGenesisHashResponse{}
	mi := &file_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGenesisHashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGenesisHashResponse) ProtoMessage() {}

func (x *GetGenesisHashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGenesisHashResponse.ProtoReflect.Descriptor instead.
func (*GetGenesisHashResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *GetGenesisHashResponse) GetGenesisHash() []byte {
	if x != nil {
		return x.GenesisHash
	}
	return nil
}

type GetBlockRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Slot               uint64                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	TransactionDetails TransactionDetails     `protobuf:"varint,2,opt,name=transactionDetails,proto3,enum=bds.svm.TransactionDetails" json:"transactionDetails,omitempty"`
	// Inverted so the proto3 default (false) matches Agave's default
	// (rewards: true).
	ExcludeRewards bool `protobuf:"varint,3,opt,name=excludeRewards,proto3" json:"excludeRewards,omitempty"`
	// Only valid value today is 0. Absent => legacy-only client: a block
	// containing a v0 transaction fails with FAILED_PRECONDITION (-32015).
	MaxSupportedTransactionVersion *uint32    `protobuf:"varint,4,opt,name=maxSupportedTransactionVersion,proto3,oneof" json:"maxSupportedTransactionVersion,omitempty"`
	Commitment                     Commitment `protobuf:"varint,5,opt,name=commitment,proto3,enum=bds.svm.Commitment" json:"commitment,omitempty"`
	MinContextSlot                 *uint64    `protobuf:"varint,6,opt,name=minContextSlot,proto3,oneof" json:"minContextSlot,omitempty"`
	// Cluster identity assertion (ADR-0014 pattern); NOT_FOUND on mismatch.
	GenesisHash   []byte `protobuf:"bytes,7,opt,name=genesisHash,proto3,oneof" json:"genesisHash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockRequest) Reset() {
	*x = GetBlockRequest{}
	mi := &file_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockRequest) ProtoMessage() {}

func (x *GetBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockRequest.ProtoReflect.Descriptor instead.
func (*GetBlockRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *GetBlockRequest) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *GetBlockRequest) GetTransactionDetails() TransactionDetails {
	if x != nil {
		return x.TransactionDetails
	}
	return TransactionDetails_TRANSACTION_DETAILS_FULL
}

func (x *GetBlockRequest) GetExcludeRewards() bool {
	if x != nil {
		return x.ExcludeRewards
	}
	return false
}

func (x *GetBlockRequest) GetMaxSupportedTransactionVersion() uint32 {
	if x != nil && x.MaxSupportedTransactionVersion != nil {
		return *x.MaxSupportedTransactionVersion
	}
	return 0
}

func (x *GetBlockRequest) GetCommitment() Commitment {
	if x != nil {
		return x.Commitment
	}
	return Commitment_COMMITMENT_FINALIZED
}

func (x *GetBlockRequest) GetMinContextSlot() uint64 {
	if x != nil && x.MinContextSlot != nil {
		return *x.MinContextSlot
	}
	return 0
}

func (x *GetBlockRequest) GetGenesisHash() []byte {
	if x != nil {
		return x.GenesisHash
	}
	return nil
}

type GetBlockResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	SlotStatus SlotStatus             `protobuf:"varint,1,opt,name=slotStatus,proto3,enum=bds.svm.SlotStatus" json:"slotStatus,omitempty"`
	// Unset when slotStatus == SLOT_SKIPPED.
	Block *ConfirmedBlock `protobuf:"bytes,2,opt,name=block,proto3" json:"block,omitempty"`
	// For TRANSACTION_DETAILS_SIGNATURES the block carries no transactions;
	// the flat signature list rides here instead.
	Signatures    [][]byte `protobuf:"bytes,3,rep,name=signatures,proto3" json:"signatures,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockResponse) Reset() {
	*x = GetBlockResponse{}
	mi := &file_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockResponse) ProtoMessage() {}

func (x *GetBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockResponse.ProtoReflect.Descriptor instead.
func (*GetBlockResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *GetBlockResponse) GetSlotStatus() SlotStatus {
	if x != nil {
		return x.SlotStatus
	}
	return SlotStatus_SLOT_PRESENT
}

func (x *GetBlockResponse) GetBlock() *ConfirmedBlock {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *GetBlockResponse) GetSignatures() [][]byte {
	if x != nil {
		return x.Signatures
	}
	return nil
}

type GetBlocksRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	StartSlot uint64                 `protobuf:"varint,1,opt,name=startSlot,proto3" json:"startSlot,omitempty"`
	// Inclusive. Range capped at 500000 (Agave parity); INVALID_ARGUMENT above.
	EndSlot        uint64     `protobuf:"varint,2,opt,name=endSlot,proto3" json:"endSlot,omitempty"`
	Commitment     Commitment `protobuf:"varint,3,opt,name=commitment,proto3,enum=bds.svm.Commitment" json:"commitment,omitempty"`
	GenesisHash    []byte     `protobuf:"bytes,4,opt,name=genesisHash,proto3,oneof" json:"genesisHash,omitempty"`
	MinContextSlot *uint64    `protobuf:"varint,5,opt,name=minContextSlot,proto3,oneof" json:"minContextSlot,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetBlocksRequest) Reset() {
	*x = GetBlocksRequest{}
	mi := &file_rpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlocksRequest) ProtoMessage() {}

func (x *GetBlocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlocksRequest.ProtoReflect.Descriptor instead.
func (*GetBlocksRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *GetBlocksRequest) GetStartSlot() uint64 {
	if x != nil {
		return x.StartSlot
	}
	return 0
}

func (x *GetBlocksRequest) GetEndSlot() uint64 {
	if x != nil {
		return x.EndSlot
	}
	return 0
}

func (x *GetBlocksRequest) GetCommitment() Commitment {
	if x != nil {
		return x.Commitment
	}
	return Commitment_COMMITMENT_FINALIZED
}

func (x *GetBlocksRequest) GetGenesisHash() []byte {
	if x != nil {
		return x.GenesisHash
	}
	return nil
}

func (x *GetBlocksRequest) GetMinContextSlot() uint64 {
	if x != nil && x.MinContextSlot != nil {
		return *x.MinContextSlot
	}
	return 0
}

type GetBlocksWithLimitRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	StartSlot uint64                 `protobuf:"varint,1,opt,name=startSlot,proto3" json:"startSlot,omitempty"`
	// Capped at 500000 (Agave parity).
	Limit          uint64     `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Commitment     Commitment `protobuf:"varint,3,opt,name=commitment,proto3,enum=bds.svm.Commitment" json:"commitment,omitempty"`
	GenesisHash    []byte     `protobuf:"bytes,4,opt,name=genesisHash,proto3,oneof" json:"genesisHash,omitempty"`
	MinContextSlot *uint64    `protobuf:"varint,5,opt,name=minContextSlot,proto3,oneof" json:"minContextSlot,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetBlocksWithLimitRequest) Reset() {
	*x = GetBlocksWithLimitRequest{}
	mi := &file_rpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlocksWithLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlocksWithLimitRequest) ProtoMessage() {}

func (x *GetBlocksWithLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlocksWithLimitRequest.ProtoReflect.Descriptor instead.
func (*GetBlocksWithLimitRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *GetBlocksWithLimitRequest) GetStartSlot() uint64 {
	if x != nil {
		return x.StartSlot
	}
	return 0
}

func (x *GetBlocksWithLimitRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetBlocksWithLimitRequest) GetCommitment() Commitment {
	if x != nil {
		return x.Commitment
	}
	return Commitment_COMMITMENT_FINALIZED
}

func (x *GetBlocksWithLimitRequest) GetGenesisHash() []byte {
	if x != nil {
		return x.GenesisHash
	}
	return nil
}

func (x *GetBlocksWithLimitRequest) GetMinContextSlot() uint64 {
	if x != nil && x.MinContextSlot != nil {
		return *x.MinContextSlot
	}
	return 0
}

type GetBlocksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slots         []uint64               `protobuf:"varint,1,rep,packed,name=slots,proto3" json:"slots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlocksResponse) Reset() {
	*x = GetBlocksResponse{}
	mi := &file_rpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlocksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlocksResponse) ProtoMessage() {}

func (x *GetBlocksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlocksResponse.ProtoReflect.Descriptor instead.
func (*GetBlocksResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *GetBlocksResponse) GetSlots() []uint64 {
	if x != nil {
		return x.Slots
	}
	return nil
}

type GetTransactionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 64-byte transaction signature (the transaction id).
	Signature                      []byte     `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	MaxSupportedTransactionVersion *uint32    `protobuf:"varint,2,opt,name=maxSupportedTransactionVersion,proto3,oneof" json:"maxSupportedTransactionVersion,omitempty"`
	Commitment                     Commitment `protobuf:"varint,3,opt,name=commitment,proto3,enum=bds.svm.Commitment" json:"commitment,omitempty"`
	GenesisHash                    []byte     `protobuf:"bytes,4,opt,name=genesisHash,proto3,oneof" json:"genesisHash,omitempty"`
	MinContextSlot                 *uint64    `protobuf:"varint,5,opt,name=minContextSlot,proto3,oneof" json:"minContextSlot,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *GetTransactionRequest) Reset() {
	*x = GetTransactionRequest{}
	mi := &file_rpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionRequest) ProtoMessage() {}

func (x *GetTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{7}
}

func (x *GetTransactionRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *GetTransactionRequest) GetMaxSupportedTransactionVersion() uint32 {
	if x != nil && x.MaxSupportedTransactionVersion != nil {
		return *x.MaxSupportedTransactionVersion
	}
	return 0
}

func (x *GetTransactionRequest) GetCommitment() Commitment {
	if x != nil {
		return x.Commitment
	}
	return Commitment_COMMITMENT_FINALIZED
}

func (x *GetTransactionRequest) GetGenesisHash() []byte {
	if x != nil {
		return x.GenesisHash
	}
	return nil
}

func (x *GetTransactionRequest) GetMinContextSlot() uint64 {
	if x != nil && x.MinContextSlot != nil {
		return *x.MinContextSlot
	}
	return 0
}

type GetTransactionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unset => not found (JSON-RPC `result: null`).
	Transaction   *ConfirmedTransaction `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Slot          uint64                `protobuf:"varint,2,opt,name=slot,proto3" json:"slot,omitempty"`
	BlockTime     *int64                `protobuf:"varint,3,opt,name=blockTime,proto3,oneof" json:"blockTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionResponse) Reset() {
	*x = GetTransactionResponse{}
	mi := &file_rpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionResponse) ProtoMessage() {}

func (x *GetTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{8}
}

func (x *GetTransactionResponse) GetTransaction() *ConfirmedTransaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *GetTransactionResponse) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *GetTransactionResponse) GetBlockTime() int64 {
	if x != nil && x.BlockTime != nil {
		return *x.BlockTime
	}
	return 0
}

type GetBlockTimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          uint64                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	GenesisHash   []byte                 `protobuf:"bytes,2,opt,name=genesisHash,proto3,oneof" json:"genesisHash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockTimeRequest) Reset() {
	*x = GetBlockTimeRequest{}
	mi := &file_rpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockTimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockTimeRequest) ProtoMessage() {}

func (x *GetBlockTimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockTimeRequest.ProtoReflect.Descriptor instead.
func (*GetBlockTimeRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{9}
}

func (x *GetBlockTimeRequest) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *GetBlockTimeRequest) GetGenesisHash() []byte {
	if x != nil {
		return x.GenesisHash
	}
	return nil
}

type GetBlockTimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotStatus    SlotStatus             `protobuf:"varint,1,opt,name=slotStatus,proto3,enum=bds.svm.SlotStatus" json:"slotStatus,omitempty"`
	BlockTime     *int64                 `protobuf:"varint,2,opt,name=blockTime,proto3,oneof" json:"blockTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockTimeResponse) Reset() {
	*x = GetBlockTimeResponse{}
	mi := &file_rpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockTimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockTimeResponse) ProtoMessage() {}

func (x *GetBlockTimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockTimeResponse.ProtoReflect.Descriptor instead.
func (*GetBlockTimeResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{10}
}

func (x *GetBlockTimeResponse) GetSlotStatus() SlotStatus {
	if x != nil {
		return x.SlotStatus
	}
	return SlotStatus_SLOT_PRESENT
}

func (x *GetBlockTimeResponse) GetBlockTime() int64 {
	if x != nil && x.BlockTime != nil {
		return *x.BlockTime
	}
	return 0
}

type GetFirstAvailableBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GenesisHash   []byte                 `protobuf:"bytes,1,opt,name=genesisHash,proto3,oneof" json:"genesisHash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFirstAvailableBlockRequest) Reset() {
	*x = GetFirstAvailableBlockRequest{}
	mi := &file_rpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFirstAvailableBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFirstAvailableBlockRequest) ProtoMessage() {}

func (x *GetFirstAvailableBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFirstAvailableBlockRequest.ProtoReflect.Descriptor instead.
func (*GetFirstAvailableBlockRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{11}
}

func (x *GetFirstAvailableBlockRequest) GetGenesisHash() []byte {
	if x != nil {
		return x.GenesisHash
	}
	return nil
}

type GetFirstAvailableBlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          uint64                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFirstAvailableBlockResponse) Reset() {
	*x = GetFirstAvailableBlockResponse{}
	mi := &file_rpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFirstAvailableBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFirstAvailableBlockResponse) ProtoMessage() {}

func (x *GetFirstAvailableBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFirstAvailableBlockResponse.ProtoReflect.Descriptor instead.
func (*GetFirstAvailableBlockResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{12}
}

func (x *GetFirstAvailableBlockResponse) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

type GetSignatureStatusesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Up to 256 signatures (Agave parity).
	Signatures    [][]byte `protobuf:"bytes,1,rep,name=signatures,proto3" json:"signatures,omitempty"`
	GenesisHash   []byte   `protobuf:"bytes,2,opt,name=genesisHash,proto3,oneof" json:"genesisHash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSignatureStatusesRequest) Reset() {
	*x = GetSignatureStatusesRequest{}
	mi := &file_rpc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSignatureStatusesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSignatureStatusesRequest) ProtoMessage() {}

func (x *GetSignatureStatusesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSignatureStatusesRequest.ProtoReflect.Descriptor instead.
func (*GetSignatureStatusesRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{13}
}

func (x *GetSignatureStatusesRequest) GetSignatures() [][]byte {
	if x != nil {
		return x.Signatures
	}
	return nil
}

func (x *GetSignatureStatusesRequest) GetGenesisHash() []byte {
	if x != nil {
		return x.GenesisHash
	}
	return nil
}

type SignatureStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unset slot + unset confirmationStatus encoding is avoided by `found`.
	Found bool   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Slot  uint64 `protobuf:"varint,2,opt,name=slot,proto3" json:"slot,omitempty"`
	// JSON-stringified TransactionError; absent = success.
	Err                *string    `protobuf:"bytes,3,opt,name=err,proto3,oneof" json:"err,omitempty"`
	ConfirmationStatus Commitment `protobuf:"varint,4,opt,name=confirmationStatus,proto3,enum=bds.svm.Commitment" json:"confirmationStatus,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SignatureStatus) Reset() {
	*x = SignatureStatus{}
	mi := &file_rpc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignatureStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignatureStatus) ProtoMessage() {}

func (x *SignatureStatus) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignatureStatus.ProtoReflect.Descriptor instead.
func (*SignatureStatus) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{14}
}

func (x *SignatureStatus) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *SignatureStatus) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *SignatureStatus) GetErr() string {
	if x != nil && x.Err != nil {
		return *x.Err
	}
	return ""
}

func (x *SignatureStatus) GetConfirmationStatus() Commitment {
	if x != nil {
		return x.ConfirmationStatus
	}
	return Commitment_COMMITMENT_FINALIZED
}

type GetSignatureStatusesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Parallel to the request order.
	Statuses      []*SignatureStatus `protobuf:"bytes,1,rep,name=statuses,proto3" json:"statuses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSignatureStatusesResponse) Reset() {
	*x = GetSignatureStatusesResponse{}
	mi := &file_rpc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSignatureStatusesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSignatureStatusesResponse) ProtoMessage() {}

func (x *GetSignatureStatusesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSignatureStatusesResponse.ProtoReflect.Descriptor instead.
func (*GetSignatureStatusesResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{15}
}

func (x *GetSignatureStatusesResponse) GetStatuses() []*SignatureStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

type GetSignaturesForAddressRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 32-byte account address.
	Address []byte `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// Exclusive cursor: start searching backwards from this signature.
	Before []byte `protobuf:"bytes,2,opt,name=before,proto3,oneof" json:"before,omitempty"`
	// Exclusive cursor: stop when this signature is reached.
	Until []byte `protobuf:"bytes,3,opt,name=until,proto3,oneof" json:"until,omitempty"`
	// 1..=1000; 0 => default 1000.
	Limit          uint32     `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Commitment     Commitment `protobuf:"varint,5,opt,name=commitment,proto3,enum=bds.svm.Commitment" json:"commitment,omitempty"`
	GenesisHash    []byte     `protobuf:"bytes,6,opt,name=genesisHash,proto3,oneof" json:"genesisHash,omitempty"`
	MinContextSlot *uint64    `protobuf:"varint,7,opt,name=minContextSlot,proto3,oneof" json:"minContextSlot,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetSignaturesForAddressRequest) Reset() {
	*x = GetSignaturesForAddressRequest{}
	mi := &file_rpc_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSignaturesForAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSignaturesForAddressRequest) ProtoMessage() {}

func (x *GetSignaturesForAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSignaturesForAddressRequest.ProtoReflect.Descriptor instead.
func (*GetSignaturesForAddressRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{16}
}

func (x *GetSignaturesForAddressRequest) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *GetSignaturesForAddressRequest) GetBefore() []byte {
	if x != nil {
		return x.Before
	}
	return nil
}

func (x *GetSignaturesForAddressRequest) GetUntil() []byte {
	if x != nil {
		return x.Until
	}
	return nil
}

func (x *GetSignaturesForAddressRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetSignaturesForAddressRequest) GetCommitment() Commitment {
	if x != nil {
		return x.Commitment
	}
	return Commitment_COMMITMENT_FINALIZED
}

func (x *GetSignaturesForAddressRequest) GetGenesisHash() []byte {
	if x != nil {
		return x.GenesisHash
	}
	return nil
}

func (x *GetSignaturesForAddressRequest) GetMinContextSlot() uint64 {
	if x != nil && x.MinContextSlot != nil {
		return *x.MinContextSlot
	}
	return 0
}

type SignatureInfo struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Signature []byte                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	Slot      uint64                 `protobuf:"varint,2,opt,name=slot,proto3" json:"slot,omitempty"`
	// JSON-stringified TransactionError; absent = success.
	Err *string `protobuf:"bytes,3,opt,name=err,proto3,oneof" json:"err,omitempty"`
	// Agave-formatted memo string ("[len] text"; multiple joined by "; ").
	Memo          *string `protobuf:"bytes,4,opt,name=memo,proto3,oneof" json:"memo,omitempty"`
	BlockTime     *int64  `protobuf:"varint,5,opt,name=blockTime,proto3,oneof" json:"blockTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignatureInfo) Reset() {
	*x = SignatureInfo{}
	mi := &file_rpc_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignatureInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignatureInfo) ProtoMessage() {}

func (x *SignatureInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignatureInfo.ProtoReflect.Descriptor instead.
func (*SignatureInfo) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{17}
}

func (x *SignatureInfo) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SignatureInfo) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *SignatureInfo) GetErr() string {
	if x != nil && x.Err != nil {
		return *x.Err
	}
	return ""
}

func (x *SignatureInfo) GetMemo() string {
	if x != nil && x.Memo != nil {
		return *x.Memo
	}
	return ""
}

func (x *SignatureInfo) GetBlockTime() int64 {
	if x != nil && x.BlockTime != nil {
		return *x.BlockTime
	}
	return 0
}

type GetSignaturesForAddressResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Newest-first.
	Signatures    []*SignatureInfo `protobuf:"bytes,1,rep,name=signatures,proto3" json:"signatures,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSignaturesForAddressResponse) Reset() {
	*x = GetSignaturesForAddressResponse{}
	mi := &file_rpc_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSignaturesForAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSignaturesForAddressResponse) ProtoMessage() {}

func (x *GetSignaturesForAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSignaturesForAddressResponse.ProtoReflect.Descriptor instead.
func (*GetSignaturesForAddressResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{18}
}

func (x *GetSignaturesForAddressResponse) GetSignatures() []*SignatureInfo {
	if x != nil {
		return x.Signatures
	}
	return nil
}

var File_rpc_proto protoreflect.FileDescriptor

const file_rpc_proto_rawDesc = "" +
	"\n" +
	"\trpc.proto\x12\abds.svm\x1a\fmodels.proto\"\x17\n" +
	"\x15GetGenesisHashRequest\":\n" +
	"\x16GetGenesisHashResponse\x12 \n" +
	"\vgenesisHash\x18\x01 \x01(\fR\vgenesisHash\"\xb6\x03\n" +
	"\x0fGetBlockRequest\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x04R\x04slot\x12K\n" +
	"\x12transactionDetails\x18\x02 \x01(\x0e2\x1b.bds.svm.TransactionDetailsR\x12transactionDetails\x12&\n" +
	"\x0eexcludeRewards\x18\x03 \x01(\bR\x0eexcludeRewards\x12K\n" +
	"\x1emaxSupportedTransactionVersion\x18\x04 \x01(\rH\x00R\x1emaxSupportedTransactionVersion\x88\x01\x01\x123\n" +
	"\n" +
	"commitment\x18\x05 \x01(\x0e2\x13.bds.svm.CommitmentR\n" +
	"commitment\x12+\n" +
	"\x0eminContextSlot\x18\x06 \x01(\x04H\x01R\x0eminContextSlot\x88\x01\x01\x12%\n" +
	"\vgenesisHash\x18\a \x01(\fH\x02R\vgenesisHash\x88\x01\x01B!\n" +
	"\x1f_maxSupportedTransactionVersionB\x11\n" +
	"\x0f_minContextSlotB\x0e\n" +
	"\f_genesisHash\"\x96\x01\n" +
	"\x10GetBlockResponse\x123\n" +
	"\n" +
	"slotStatus\x18\x01 \x01(\x0e2\x13.bds.svm.SlotStatusR\n" +
	"slotStatus\x12-\n" +
	"\x05block\x18\x02 \x01(\v2\x17.bds.svm.ConfirmedBlockR\x05block\x12\x1e\n" +
	"\n" +
	"signatures\x18\x03 \x03(\fR\n" +
	"signatures\"\xf6\x01\n" +
	"\x10GetBlocksRequest\x12\x1c\n" +
	"\tstartSlot\x18\x01 \x01(\x04R\tstartSlot\x12\x18\n" +
	"\aendSlot\x18\x02 \x01(\x04R\aendSlot\x123\n" +
	"\n" +
	"commitment\x18\x03 \x01(\x0e2\x13.bds.svm.CommitmentR\n" +
	"commitment\x12%\n" +
	"\vgenesisHash\x18\x04 \x01(\fH\x00R\vgenesisHash\x88\x01\x01\x12+\n" +
	"\x0eminContextSlot\x18\x05 \x01(\x04H\x01R\x0eminContextSlot\x88\x01\x01B\x0e\n" +
	"\f_genesisHashB\x11\n" +
	"\x0f_minContextSlot\"\xfb\x01\n" +
	"\x19GetBlocksWithLimitRequest\x12\x1c\n" +
	"\tstartSlot\x18\x01 \x01(\x04R\tstartSlot\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x04R\x05limit\x123\n" +
	"\n" +
	"commitment\x18\x03 \x01(\x0e2\x13.bds.svm.CommitmentR\n" +
	"commitment\x12%\n" +
	"\vgenesisHash\x18\x04 \x01(\fH\x00R\vgenesisHash\x88\x01\x01\x12+\n" +
	"\x0eminContextSlot\x18\x05 \x01(\x04H\x01R\x0eminContextSlot\x88\x01\x01B\x0e\n" +
	"\f_genesisHashB\x11\n" +
	"\x0f_minContextSlot\")\n" +
	"\x11GetBlocksResponse\x12\x14\n" +
	"\x05slots\x18\x01 \x03(\x04R\x05slots\"\xd1\x02\n" +
	"\x15GetTransactionRequest\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature\x12K\n" +
	"\x1emaxSupportedTransactionVersion\x18\x02 \x01(\rH\x00R\x1emaxSupportedTransactionVersion\x88\x01\x01\x123\n" +
	"\n" +
	"commitment\x18\x03 \x01(\x0e2\x13.bds.svm.CommitmentR\n" +
	"commitment\x12%\n" +
	"\vgenesisHash\x18\x04 \x01(\fH\x01R\vgenesisHash\x88\x01\x01\x12+\n" +
	"\x0eminContextSlot\x18\x05 \x01(\x04H\x02R\x0eminContextSlot\x88\x01\x01B!\n" +
	"\x1f_maxSupportedTransactionVersionB\x0e\n" +
	"\f_genesisHashB\x11\n" +
	"\x0f_minContextSlot\"\x9e\x01\n" +
	"\x16GetTransactionResponse\x12?\n" +
	"\vtransaction\x18\x01 \x01(\v2\x1d.bds.svm.ConfirmedTransactionR\vtransaction\x12\x12\n" +
	"\x04slot\x18\x02 \x01(\x04R\x04slot\x12!\n" +
	"\tblockTime\x18\x03 \x01(\x03H\x00R\tblockTime\x88\x01\x01B\f\n" +
	"\n" +
	"_blockTime\"`\n" +
	"\x13GetBlockTimeRequest\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x04R\x04slot\x12%\n" +
	"\vgenesisHash\x18\x02 \x01(\fH\x00R\vgenesisHash\x88\x01\x01B\x0e\n" +
	"\f_genesisHash\"|\n" +
	"\x14GetBlockTimeResponse\x123\n" +
	"\n" +
	"slotStatus\x18\x01 \x01(\x0e2\x13.bds.svm.SlotStatusR\n" +
	"slotStatus\x12!\n" +
	"\tblockTime\x18\x02 \x01(\x03H\x00R\tblockTime\x88\x01\x01B\f\n" +
	"\n" +
	"_blockTime\"V\n" +
	"\x1dGetFirstAvailableBlockRequest\x12%\n" +
	"\vgenesisHash\x18\x01 \x01(\fH\x00R\vgenesisHash\x88\x01\x01B\x0e\n" +
	"\f_genesisHash\"4\n" +
	"\x1eGetFirstAvailableBlockResponse\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x04R\x04slot\"t\n" +
	"\x1bGetSignatureStatusesRequest\x12\x1e\n" +
	"\n" +
	"signatures\x18\x01 \x03(\fR\n" +
	"signatures\x12%\n" +
	"\vgenesisHash\x18\x02 \x01(\fH\x00R\vgenesisHash\x88\x01\x01B\x0e\n" +
	"\f_genesisHash\"\x9f\x01\n" +
	"\x0fSignatureStatus\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x12\n" +
	"\x04slot\x18\x02 \x01(\x04R\x04slot\x12\x15\n" +
	"\x03err\x18\x03 \x01(\tH\x00R\x03err\x88\x01\x01\x12C\n" +
	"\x12confirmationStatus\x18\x04 \x01(\x0e2\x13.bds.svm.CommitmentR\x12confirmationStatusB\x06\n" +
	"\x04_err\"T\n" +
	"\x1cGetSignatureStatusesResponse\x124\n" +
	"\bstatuses\x18\x01 \x03(\v2\x18.bds.svm.SignatureStatusR\bstatuses\"\xc9\x02\n" +
	"\x1eGetSignaturesForAddressRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\fR\aaddress\x12\x1b\n" +
	"\x06before\x18\x02 \x01(\fH\x00R\x06before\x88\x01\x01\x12\x19\n" +
	"\x05until\x18\x03 \x01(\fH\x01R\x05until\x88\x01\x01\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\rR\x05limit\x123\n" +
	"\n" +
	"commitment\x18\x05 \x01(\x0e2\x13.bds.svm.CommitmentR\n" +
	"commitment\x12%\n" +
	"\vgenesisHash\x18\x06 \x01(\fH\x02R\vgenesisHash\x88\x01\x01\x12+\n" +
	"\x0eminContextSlot\x18\a \x01(\x04H\x03R\x0eminContextSlot\x88\x01\x01B\t\n" +
	"\a_beforeB\b\n" +
	"\x06_untilB\x0e\n" +
	"\f_genesisHashB\x11\n" +
	"\x0f_minContextSlot\"\xb3\x01\n" +
	"\rSignatureInfo\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature\x12\x12\n" +
	"\x04slot\x18\x02 \x01(\x04R\x04slot\x12\x15\n" +
	"\x03err\x18\x03 \x01(\tH\x00R\x03err\x88\x01\x01\x12\x17\n" +
	"\x04memo\x18\x04 \x01(\tH\x01R\x04memo\x88\x01\x01\x12!\n" +
	"\tblockTime\x18\x05 \x01(\x03H\x02R\tblockTime\x88\x01\x01B\x06\n" +
	"\x04_errB\a\n" +
	"\x05_memoB\f\n" +
	"\n" +
	"_blockTime\"Y\n" +
	"\x1fGetSignaturesForAddressResponse\x126\n" +
	"\n" +
	"signatures\x18\x01 \x03(\v2\x16.bds.svm.SignatureInfoR\n" +
	"signatures*@\n" +
	"\n" +
	"Commitment\x12\x18\n" +
	"\x14COMMITMENT_FINALIZED\x10\x00\x12\x18\n" +
	"\x14COMMITMENT_CONFIRMED\x10\x01*0\n" +
	"\n" +
	"SlotStatus\x12\x10\n" +
	"\fSLOT_PRESENT\x10\x00\x12\x10\n" +
	"\fSLOT_SKIPPED\x10\x01*\x96\x01\n" +
	"\x12TransactionDetails\x12\x1c\n" +
	"\x18TRANSACTION_DETAILS_FULL\x10\x00\x12 \n" +
	"\x1cTRANSACTION_DETAILS_ACCOUNTS\x10\x01\x12\"\n" +
	"\x1eTRANSACTION_DETAILS_SIGNATURES\x10\x02\x12\x1c\n" +
	"\x18TRANSACTION_DETAILS_NONE\x10\x032\x9d\x06\n" +
	"\x0fRPCQueryService\x12Q\n" +
	"\x0eGetGenesisHash\x12\x1e.bds.svm.GetGenesisHashRequest\x1a\x1f.bds.svm.GetGenesisHashResponse\x12?\n" +
	"\bGetBlock\x12\x18.bds.svm.GetBlockRequest\x1a\x19.bds.svm.GetBlockResponse\x12B\n" +
	"\tGetBlocks\x12\x19.bds.svm.GetBlocksRequest\x1a\x1a.bds.svm.GetBlocksResponse\x12T\n" +
	"\x12GetBlocksWithLimit\x12\".bds.svm.GetBlocksWithLimitRequest\x1a\x1a.bds.svm.GetBlocksResponse\x12Q\n" +
	"\x0eGetTransaction\x12\x1e.bds.svm.GetTransactionRequest\x1a\x1f.bds.svm.GetTransactionResponse\x12K\n" +
	"\fGetBlockTime\x12\x1c.bds.svm.GetBlockTimeRequest\x1a\x1d.bds.svm.GetBlockTimeResponse\x12i\n" +
	"\x16GetFirstAvailableBlock\x12&.bds.svm.GetFirstAvailableBlockRequest\x1a'.bds.svm.GetFirstAvailableBlockResponse\x12c\n" +
	"\x14GetSignatureStatuses\x12$.bds.svm.GetSignatureStatusesRequest\x1a%.bds.svm.GetSignatureStatusesResponse\x12l\n" +
	"\x17GetSignaturesForAddress\x12'.bds.svm.GetSignaturesForAddressRequest\x1a(.bds.svm.GetSignaturesForAddressResponseB4Z2github.com/blockchain-data-standards/manifesto/svmb\x06proto3"

var (
	file_rpc_proto_rawDescOnce sync.Once
	file_rpc_proto_rawDescData []byte
)

func file_rpc_proto_rawDescGZIP() []byte {
	file_rpc_proto_rawDescOnce.Do(func() {
		file_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_proto_rawDesc), len(file_rpc_proto_rawDesc)))
	})
	return file_rpc_proto_rawDescData
}

var file_rpc_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_rpc_proto_goTypes = []any{
	(Commitment)(0),                         // 0: bds.svm.Commitment
	(SlotStatus)(0),                         // 1: bds.svm.SlotStatus
	(TransactionDetails)(0),                 // 2: bds.svm.TransactionDetails
	(*GetGenesisHashRequest)(nil),           // 3: bds.svm.GetGenesisHashRequest
	(*GetGenesisHashResponse)(nil),          // 4: bds.svm.GetGenesisHashResponse
	(*GetBlockRequest)(nil),                 // 5: bds.svm.GetBlockRequest
	(*GetBlockResponse)(nil),                // 6: bds.svm.GetBlockResponse
	(*GetBlocksRequest)(nil),                // 7: bds.svm.GetBlocksRequest
	(*GetBlocksWithLimitRequest)(nil),       // 8: bds.svm.GetBlocksWithLimitRequest
	(*GetBlocksResponse)(nil),               // 9: bds.svm.GetBlocksResponse
	(*GetTransactionRequest)(nil),           // 10: bds.svm.GetTransactionRequest
	(*GetTransactionResponse)(nil),          // 11: bds.svm.GetTransactionResponse
	(*GetBlockTimeRequest)(nil),             // 12: bds.svm.GetBlockTimeRequest
	(*GetBlockTimeResponse)(nil),            // 13: bds.svm.GetBlockTimeResponse
	(*GetFirstAvailableBlockRequest)(nil),   // 14: bds.svm.GetFirstAvailableBlockRequest
	(*GetFirstAvailableBlockResponse)(nil),  // 15: bds.svm.GetFirstAvailableBlockResponse
	(*GetSignatureStatusesRequest)(nil),     // 16: bds.svm.GetSignatureStatusesRequest
	(*SignatureStatus)(nil),                 // 17: bds.svm.SignatureStatus
	(*GetSignatureStatusesResponse)(nil),    // 18: bds.svm.GetSignatureStatusesResponse
	(*GetSignaturesForAddressRequest)(nil),  // 19: bds.svm.GetSignaturesForAddressRequest
	(*SignatureInfo)(nil),                   // 20: bds.svm.SignatureInfo
	(*GetSignaturesForAddressResponse)(nil), // 21: bds.svm.GetSignaturesForAddressResponse
	(*ConfirmedBlock)(nil),                  // 22: bds.svm.ConfirmedBlock
	(*ConfirmedTransaction)(nil),            // 23: bds.svm.ConfirmedTransaction
}
var file_rpc_proto_depIdxs = []int32{
	2,  // 0: bds.svm.GetBlockRequest.transactionDetails:type_name -> bds.svm.TransactionDetails
	0,  // 1: bds.svm.GetBlockRequest.commitment:type_name -> bds.svm.Commitment
	1,  // 2: bds.svm.GetBlockResponse.slotStatus:type_name -> bds.svm.SlotStatus
	22, // 3: bds.svm.GetBlockResponse.block:type_name -> bds.svm.ConfirmedBlock
	0,  // 4: bds.svm.GetBlocksRequest.commitment:type_name -> bds.svm.Commitment
	0,  // 5: bds.svm.GetBlocksWithLimitRequest.commitment:type_name -> bds.svm.Commitment
	0,  // 6: bds.svm.GetTransactionRequest.commitment:type_name -> bds.svm.Commitment
	23, // 7: bds.svm.GetTransactionResponse.transaction:type_name -> bds.svm.ConfirmedTransaction
	1,  // 8: bds.svm.GetBlockTimeResponse.slotStatus:type_name -> bds.svm.SlotStatus
	0,  // 9: bds.svm.SignatureStatus.confirmationStatus:type_name -> bds.svm.Commitment
	17, // 10: bds.svm.GetSignatureStatusesResponse.statuses:type_name -> bds.svm.SignatureStatus
	0,  // 11: bds.svm.GetSignaturesForAddressRequest.commitment:type_name -> bds.svm.Commitment
	20, // 12: bds.svm.GetSignaturesForAddressResponse.signatures:type_name -> bds.svm.SignatureInfo
	3,  // 13: bds.svm.RPCQueryService.GetGenesisHash:input_type -> bds.svm.GetGenesisHashRequest
	5,  // 14: bds.svm.RPCQueryService.GetBlock:input_type -> bds.svm.GetBlockRequest
	7,  // 15: bds.svm.RPCQueryService.GetBlocks:input_type -> bds.svm.GetBlocksRequest
	8,  // 16: bds.svm.RPCQueryService.GetBlocksWithLimit:input_type -> bds.svm.GetBlocksWithLimitRequest
	10, // 17: bds.svm.RPCQueryService.GetTransaction:input_type -> bds.svm.GetTransactionRequest
	12, // 18: bds.svm.RPCQueryService.GetBlockTime:input_type -> bds.svm.GetBlockTimeRequest
	14, // 19: bds.svm.RPCQueryService.GetFirstAvailableBlock:input_type -> bds.svm.GetFirstAvailableBlockRequest
	16, // 20: bds.svm.RPCQueryService.GetSignatureStatuses:input_type -> bds.svm.GetSignatureStatusesRequest
	19, // 21: bds.svm.RPCQueryService.GetSignaturesForAddress:input_type -> bds.svm.GetSignaturesForAddressRequest
	4,  // 22: bds.svm.RPCQueryService.GetGenesisHash:output_type -> bds.svm.GetGenesisHashResponse
	6,  // 23: bds.svm.RPCQueryService.GetBlock:output_type -> bds.svm.GetBlockResponse
	9,  // 24: bds.svm.RPCQueryService.GetBlocks:output_type -> bds.svm.GetBlocksResponse
	9,  // 25: bds.svm.RPCQueryService.GetBlocksWithLimit:output_type -> bds.svm.GetBlocksResponse
	11, // 26: bds.svm.RPCQueryService.GetTransaction:output_type -> bds.svm.GetTransactionResponse
	13, // 27: bds.svm.RPCQueryService.GetBlockTime:output_type -> bds.svm.GetBlockTimeResponse
	15, // 28: bds.svm.RPCQueryService.GetFirstAvailableBlock:output_type -> bds.svm.GetFirstAvailableBlockResponse
	18, // 29: bds.svm.RPCQueryService.GetSignatureStatuses:output_type -> bds.svm.GetSignatureStatusesResponse
	21, // 30: bds.svm.RPCQueryService.GetSignaturesForAddress:output_type -> bds.svm.GetSignaturesForAddressResponse
	22, // [22:31] is the sub-list for method output_type
	13, // [13:22] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_rpc_proto_init() }
func file_rpc_proto_init() {
	if File_rpc_proto != nil {
		return
	}
	file_models_proto_init()
	file_rpc_proto_msgTypes[2].OneofWrappers = []any{}
	file_rpc_proto_msgTypes[4].OneofWrappers = []any{}
	file_rpc_proto_msgTypes[5].OneofWrappers = []any{}
	file_rpc_proto_msgTypes[7].OneofWrappers = []any{}
	file_rpc_proto_msgTypes[8].OneofWrappers = []any{}
	file_rpc_proto_msgTypes[9].OneofWrappers = []any{}
	file_rpc_proto_msgTypes[10].OneofWrappers = []any{}
	file_rpc_proto_msgTypes[11].OneofWrappers = []any{}
	file_rpc_proto_msgTypes[13].OneofWrappers = []any{}
	file_rpc_proto_msgTypes[14].OneofWrappers = []any{}
	file_rpc_proto_msgTypes[16].OneofWrappers = []any{}
	file_rpc_proto_msgTypes[17].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_proto_rawDesc), len(file_rpc_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_proto_goTypes,
		DependencyIndexes: file_rpc_proto_depIdxs,
		EnumInfos:         file_rpc_proto_enumTypes,
		MessageInfos:      file_rpc_proto_msgTypes,
	}.Build()
	File_rpc_proto = out.File
	file_rpc_proto_goTypes = nil
	file_rpc_proto_depIdxs = nil
}
