// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: rpc.proto

package svm

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RPCQueryService_GetGenesisHash_FullMethodName          = "/bds.svm.RPCQueryService/GetGenesisHash"
	RPCQueryService_GetBlock_FullMethodName                = "/bds.svm.RPCQueryService/GetBlock"
	RPCQueryService_GetBlocks_FullMethodName               = "/bds.svm.RPCQueryService/GetBlocks"
	RPCQueryService_GetBlocksWithLimit_FullMethodName      = "/bds.svm.RPCQueryService/GetBlocksWithLimit"
	RPCQueryService_GetTransaction_FullMethodName          = "/bds.svm.RPCQueryService/GetTransaction"
	RPCQueryService_GetBlockTime_FullMethodName            = "/bds.svm.RPCQueryService/GetBlockTime"
	RPCQueryService_GetFirstAvailableBlock_FullMethodName  = "/bds.svm.RPCQueryService/GetFirstAvailableBlock"
	RPCQueryService_GetSignatureStatuses_FullMethodName    = "/bds.svm.RPCQueryService/GetSignatureStatuses"
	RPCQueryService_GetSignaturesForAddress_FullMethodName = "/bds.svm.RPCQueryService/GetSignaturesForAddress"
)

// RPCQueryServiceClient is the client API for RPCQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Equivalent to the Solana JSON-RPC methods servable from immutable
// block/transaction history (the set Agave itself serves from long-term
// storage). Account-state and live-cluster-state methods are deliberately
// absent — they cannot be answered from an archive.
//
// Error/status contract (three layers, see prism plan D8):
//   - Benign absence (above tip, below floor, not ingested) => gRPC OUT_OF_RANGE.
//   - Skipped slots are DATA, not errors: OK responses carry SlotStatus so
//     consumers can cache "immutably skipped" forever and synthesize Agave's
//     -32007/-32009.
//   - Version gating (-32015) and minContextSlot (-32016) => FAILED_PRECONDITION.
//   - Server faults (dangling index reference, decode failure) => INTERNAL.
type RPCQueryServiceClient interface {
	// Cluster identity (Solana has no numeric chain id; the genesis hash is
	// the network identity, e.g. mainnet-beta
	// 5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d).
	GetGenesisHash(ctx context.Context, in *GetGenesisHashRequest, opts ...grpc.CallOption) (*GetGenesisHashResponse, error)
	// Equivalent to `getBlock` (encoding concerns live client-side; the
	// response is the structured block).
	GetBlock(ctx context.Context, in *GetBlockRequest, opts ...grpc.CallOption) (*GetBlockResponse, error)
	// Equivalent to `getBlocks`: the non-skipped slots in [startSlot, endSlot].
	GetBlocks(ctx context.Context, in *GetBlocksRequest, opts ...grpc.CallOption) (*GetBlocksResponse, error)
	// Equivalent to `getBlocksWithLimit`.
	GetBlocksWithLimit(ctx context.Context, in *GetBlocksWithLimitRequest, opts ...grpc.CallOption) (*GetBlocksResponse, error)
	// Equivalent to `getTransaction`. Not found => OK with unset transaction
	// (matching JSON-RPC `result: null`).
	GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*GetTransactionResponse, error)
	// Equivalent to `getBlockTime`.
	GetBlockTime(ctx context.Context, in *GetBlockTimeRequest, opts ...grpc.CallOption) (*GetBlockTimeResponse, error)
	// Equivalent to `getFirstAvailableBlock`: the lake's coverage floor.
	GetFirstAvailableBlock(ctx context.Context, in *GetFirstAvailableBlockRequest, opts ...grpc.CallOption) (*GetFirstAvailableBlockResponse, error)
	// Equivalent to `getSignatureStatuses` with searchTransactionHistory:true
	// semantics (archived statuses; confirmations null / finalized unless the
	// signature is only known to the live tip).
	GetSignatureStatuses(ctx context.Context, in *GetSignatureStatusesRequest, opts ...grpc.CallOption) (*GetSignatureStatusesResponse, error)
	// Equivalent to `getSignaturesForAddress`: newest-first, exclusive
	// before/until signature cursors, limit <= 1000.
	GetSignaturesForAddress(ctx context.Context, in *GetSignaturesForAddressRequest, opts ...grpc.CallOption) (*GetSignaturesForAddressResponse, error)
}

type rPCQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRPCQueryServiceClient(cc grpc.ClientConnInterface) RPCQueryServiceClient {
	return &rPCQueryServiceClient{cc}
}

func (c *rPCQueryServiceClient) GetGenesisHash(ctx context.Context, in *GetGenesisHashRequest, opts ...grpc.CallOption) (*GetGenesisHashResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGenesisHashResponse)
	err := c.cc.Invoke(ctx, RPCQueryService_GetGenesisHash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCQueryServiceClient) GetBlock(ctx context.Context, in *GetBlockRequest, opts ...grpc.CallOption) (*GetBlockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBlockResponse)
	err := c.cc.Invoke(ctx, RPCQueryService_GetBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCQueryServiceClient) GetBlocks(ctx context.Context, in *GetBlocksRequest, opts ...grpc.CallOption) (*GetBlocksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBlocksResponse)
	err := c.cc.Invoke(ctx, RPCQueryService_GetBlocks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCQueryServiceClient) GetBlocksWithLimit(ctx context.Context, in *GetBlocksWithLimitRequest, opts ...grpc.CallOption) (*GetBlocksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBlocksResponse)
	err := c.cc.Invoke(ctx, RPCQueryService_GetBlocksWithLimit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCQueryServiceClient) GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*GetTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTransactionResponse)
	err := c.cc.Invoke(ctx, RPCQueryService_GetTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCQueryServiceClient) GetBlockTime(ctx context.Context, in *GetBlockTimeRequest, opts ...grpc.CallOption) (*GetBlockTimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBlockTimeResponse)
	err := c.cc.Invoke(ctx, RPCQueryService_GetBlockTime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCQueryServiceClient) GetFirstAvailableBlock(ctx context.Context, in *GetFirstAvailableBlockRequest, opts ...grpc.CallOption) (*GetFirstAvailableBlockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFirstAvailableBlockResponse)
	err := c.cc.Invoke(ctx, RPCQueryService_GetFirstAvailableBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCQueryServiceClient) GetSignatureStatuses(ctx context.Context, in *GetSignatureStatusesRequest, opts ...grpc.CallOption) (*GetSignatureStatusesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSignatureStatusesResponse)
	err := c.cc.Invoke(ctx, RPCQueryService_GetSignatureStatuses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCQueryServiceClient) GetSignaturesForAddress(ctx context.Context, in *GetSignaturesForAddressRequest, opts ...grpc.CallOption) (*GetSignaturesForAddressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSignaturesForAddressResponse)
	err := c.cc.Invoke(ctx, RPCQueryService_GetSignaturesForAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RPCQueryServiceServer is the server API for RPCQueryService service.
// All implementations must embed UnimplementedRPCQueryServiceServer
// for forward compatibility.
//
// Equivalent to the Solana JSON-RPC methods servable from immutable
// block/transaction history (the set Agave itself serves from long-term
// storage). Account-state and live-cluster-state methods are deliberately
// absent — they cannot be answered from an archive.
//
// Error/status contract (three layers, see prism plan D8):
//   - Benign absence (above tip, below floor, not ingested) => gRPC OUT_OF_RANGE.
//   - Skipped slots are DATA, not errors: OK responses carry SlotStatus so
//     consumers can cache "immutably skipped" forever and synthesize Agave's
//     -32007/-32009.
//   - Version gating (-32015) and minContextSlot (-32016) => FAILED_PRECONDITION.
//   - Server faults (dangling index reference, decode failure) => INTERNAL.
type RPCQueryServiceServer interface {
	// Cluster identity (Solana has no numeric chain id; the genesis hash is
	// the network identity, e.g. mainnet-beta
	// 5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d).
	GetGenesisHash(context.Context, *GetGenesisHashRequest) (*GetGenesisHashResponse, error)
	// Equivalent to `getBlock` (encoding concerns live client-side; the
	// response is the structured block).
	GetBlock(context.Context, *GetBlockRequest) (*GetBlockResponse, error)
	// Equivalent to `getBlocks`: the non-skipped slots in [startSlot, endSlot].
	GetBlocks(context.Context, *GetBlocksRequest) (*GetBlocksResponse, error)
	// Equivalent to `getBlocksWithLimit`.
	GetBlocksWithLimit(context.Context, *GetBlocksWithLimitRequest) (*GetBlocksResponse, error)
	// Equivalent to `getTransaction`. Not found => OK with unset transaction
	// (matching JSON-RPC `result: null`).
	GetTransaction(context.Context, *GetTransactionRequest) (*GetTransactionResponse, error)
	// Equivalent to `getBlockTime`.
	GetBlockTime(context.Context, *GetBlockTimeRequest) (*GetBlockTimeResponse, error)
	// Equivalent to `getFirstAvailableBlock`: the lake's coverage floor.
	GetFirstAvailableBlock(context.Context, *GetFirstAvailableBlockRequest) (*GetFirstAvailableBlockResponse, error)
	// Equivalent to `getSignatureStatuses` with searchTransactionHistory:true
	// semantics (archived statuses; confirmations null / finalized unless the
	// signature is only known to the live tip).
	GetSignatureStatuses(context.Context, *GetSignatureStatusesRequest) (*GetSignatureStatusesResponse, error)
	// Equivalent to `getSignaturesForAddress`: newest-first, exclusive
	// before/until signature cursors, limit <= 1000.
	GetSignaturesForAddress(context.Context, *GetSignaturesForAddressRequest) (*GetSignaturesForAddressResponse, error)
	mustEmbedUnimplementedRPCQueryServiceServer()
}

// UnimplementedRPCQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRPCQueryServiceServer struct{}

func (UnimplementedRPCQueryServiceServer) GetGenesisHash(context.Context, *GetGenesisHashRequest) (*GetGenesisHashResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGenesisHash not implemented")
}
func (UnimplementedRPCQueryServiceServer) GetBlock(context.Context, *GetBlockRequest) (*GetBlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlock not implemented")
}
func (UnimplementedRPCQueryServiceServer) GetBlocks(context.Context, *GetBlocksRequest) (*GetBlocksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlocks not implemented")
}
func (UnimplementedRPCQueryServiceServer) GetBlocksWithLimit(context.Context, *GetBlocksWithLimitRequest) (*GetBlocksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlocksWithLimit not implemented")
}
func (UnimplementedRPCQueryServiceServer) GetTransaction(context.Context, *GetTransactionRequest) (*GetTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransaction not implemented")
}
func (UnimplementedRPCQueryServiceServer) GetBlockTime(context.Context, *GetBlockTimeRequest) (*GetBlockTimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlockTime not implemented")
}
func (UnimplementedRPCQueryServiceServer) GetFirstAvailableBlock(context.Context, *GetFirstAvailableBlockRequest) (*GetFirstAvailableBlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFirstAvailableBlock not implemented")
}
func (UnimplementedRPCQueryServiceServer) GetSignatureStatuses(context.Context, *GetSignatureStatusesRequest) (*GetSignatureStatusesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSignatureStatuses not implemented")
}
func (UnimplementedRPCQueryServiceServer) GetSignaturesForAddress(context.Context, *GetSignaturesForAddressRequest) (*GetSignaturesForAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSignaturesForAddress not implemented")
}
func (UnimplementedRPCQueryServiceServer) mustEmbedUnimplementedRPCQueryServiceServer() {}
func (UnimplementedRPCQueryServiceServer) testEmbeddedByValue()                         {}

// UnsafeRPCQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RPCQueryServiceServer will
// result in compilation errors.
type UnsafeRPCQueryServiceServer interface {
	mustEmbedUnimplementedRPCQueryServiceServer()
}

func RegisterRPCQueryServiceServer(s grpc.ServiceRegistrar, srv RPCQueryServiceServer) {
	// If the following call pancis, it indicates UnimplementedRPCQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RPCQueryService_ServiceDesc, srv)
}

func _RPCQueryService_GetGenesisHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGenesisHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCQueryServiceServer).GetGenesisHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPCQueryService_GetGenesisHash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCQueryServiceServer).GetGenesisHash(ctx, req.(*GetGenesisHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCQueryService_GetBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCQueryServiceServer).GetBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPCQueryService_GetBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCQueryServiceServer).GetBlock(ctx, req.(*GetBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCQueryService_GetBlocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCQueryServiceServer).GetBlocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPCQueryService_GetBlocks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCQueryServiceServer).GetBlocks(ctx, req.(*GetBlocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCQueryService_GetBlocksWithLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlocksWithLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCQueryServiceServer).GetBlocksWithLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPCQueryService_GetBlocksWithLimit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCQueryServiceServer).GetBlocksWithLimit(ctx, req.(*GetBlocksWithLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCQueryService_GetTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCQueryServiceServer).GetTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPCQueryService_GetTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCQueryServiceServer).GetTransaction(ctx, req.(*GetTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCQueryService_GetBlockTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockTimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCQueryServiceServer).GetBlockTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPCQueryService_GetBlockTime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCQueryServiceServer).GetBlockTime(ctx, req.(*GetBlockTimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCQueryService_GetFirstAvailableBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFirstAvailableBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCQueryServiceServer).GetFirstAvailableBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPCQueryService_GetFirstAvailableBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCQueryServiceServer).GetFirstAvailableBlock(ctx, req.(*GetFirstAvailableBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCQueryService_GetSignatureStatuses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSignatureStatusesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCQueryServiceServer).GetSignatureStatuses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPCQueryService_GetSignatureStatuses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCQueryServiceServer).GetSignatureStatuses(ctx, req.(*GetSignatureStatusesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCQueryService_GetSignaturesForAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSignaturesForAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCQueryServiceServer).GetSignaturesForAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPCQueryService_GetSignaturesForAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCQueryServiceServer).GetSignaturesForAddress(ctx, req.(*GetSignaturesForAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RPCQueryService_ServiceDesc is the grpc.ServiceDesc for RPCQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RPCQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bds.svm.RPCQueryService",
	HandlerType: (*RPCQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGenesisHash",
			Handler:    _RPCQueryService_GetGenesisHash_Handler,
		},
		{
			MethodName: "GetBlock",
			Handler:    _RPCQueryService_GetBlock_Handler,
		},
		{
			MethodName: "GetBlocks",
			Handler:    _RPCQueryService_GetBlocks_Handler,
		},
		{
			MethodName: "GetBlocksWithLimit",
			Handler:    _RPCQueryService_GetBlocksWithLimit_Handler,
		},
		{
			MethodName: "GetTransaction",
			Handler:    _RPCQueryService_GetTransaction_Handler,
		},
		{
			MethodName: "GetBlockTime",
			Handler:    _RPCQueryService_GetBlockTime_Handler,
		},
		{
			MethodName: "GetFirstAvailableBlock",
			Handler:    _RPCQueryService_GetFirstAvailableBlock_Handler,
		},
		{
			MethodName: "GetSignatureStatuses",
			Handler:    _RPCQueryService_GetSignatureStatuses_Handler,
		},
		{
			MethodName: "GetSignaturesForAddress",
			Handler:    _RPCQueryService_GetSignaturesForAddress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}
